src/SmartComponents/DriftTable/AddSystem.js
src/SmartComponents/DriftTable/DriftTable.js
src/SmartComponents/DriftTable/modules/actions.js
src/SmartComponents/DriftTable/modules/index.js
src/SmartComponents/DriftTable/modules/reducers.js
src/SmartComponents/DriftTable/modules/types.js
src/api.js
src/store/index.js

This is a lot of changes, as implementing the full redux workflow requires adding a number of parts.

Add redux setup for actions and reducers

---

src/Routes.js
src/index.html

With a new update to `@patternfly/patternfly-next` (which will eventually be updated to `@patternfly/patternfly`), the `page` has moved from a layout to a component and the classes will need to be updated.
This keeps the old classes as well as adding the new classes so this can be merged without breaking before or after the merge of https://github.com/RedHatInsights/insights-chrome/pull/147
Also, welcome 😄

Updating classes for upgrade to patternfly

---

.babelrc
package-lock.json
package.json
src/Routes.js
src/SmartComponents/AddSystemModal/AddSystemModal.js
src/SmartComponents/DriftPage/DriftTable/DriftTable.js
src/SmartComponents/SystemsTable/SystemsTable.js
src/SmartComponents/SystemsTable/reducers.js
src/SmartComponents/modules/reducers.js
src/store/index.js

Opening this for early stage review and placeholder. This presents the systems as a page with a set of pre-selected systems. This will convert to be embedded in a modal so the component is valid.

Add page to show systems table from inventory

---

src/index.html

We updated to use a single ESI tag in the index for more flexibility in chroming. This should make it on par with the other apps.

Updating to use single esi tag

---

src/App.js

~On hold until: https://github.com/RedHatInsights/insights-chrome/pull/165 merges~
This should work on `/insightsbeta/platform/drift`

Identify app as drift

---

src/SmartComponents/DriftPage/DriftPage.js
src/SmartComponents/DriftPage/DriftTable/DriftTable.js

Chose to add the empty state inside of the table. Mostly because it's the easiest way to do it, but can figure out how to populate the entire page with it if that won't work, we'd just need to do some restructuring.

Add empty state

---

config/base.webpack.plugins.js
config/spandx.config.js
config/webpack.common.js
package-lock.json
package.json
src/constants.js
src/entry-dev.js
src/entry.js
src/index.html

Various changes to support new URL

Migrate to cloud.redhat.com

---

src/entry-dev.js
src/entry.js

@KarelHala Tagging you for review.

Fix path name in CI env

---

src/SmartComponents/DriftPage/SearchBar/SearchBar.js

Now, if you press enter in the fact filter, it will not redirect. Nothing will happen.

Pressing enter in fact filter search bar doesn't clear compare

---

src/SmartComponents/modules/reducers.js

Based on changes here: https://github.com/RedHatInsights/drift-backend/pull/75

Update reducer to read state instead of status

---

src/SmartComponents/AddSystemModal/AddSystemModal.js
src/SmartComponents/DriftPage/DriftTable/DriftTable.js
src/SmartComponents/DriftPage/ExportButton/ExportButton.js

Change "Add Systems to Compare" to "Add systems to compare" in empty state
Change "Add System" to "Add system" in add system modal
Change "Export" to "Export to CSV" in kebab dropdown

Made text updates in 1 PR

---

src/SmartComponents/DriftPage/DriftTable/DriftTable.js
src/SmartComponents/modules/reducers.js

Also added security against facts/categories that may be uppercase.

Nested facts are now sorted correctly with regards to capitalization

---

src/App.scss
src/SmartComponents/DriftPage/DriftTable/DriftTable.js

Bug in code was causing it to not render, but now it is.

Actively sorted column includes blue bottom border

---

src/SmartComponents/AddSystemModal/AddSystemModal.js

Use auto width for system dialog

---

.babelrc
package-lock.json
package.json
profiles/local-frontend-and-api.js
src/Routes.js
src/SmartComponents/AddSystemModal/AddSystemModal.js
src/SmartComponents/BaselinesTable/BaselinesTable.js
src/SmartComponents/ExperimentalCookie/ExperimentalCookie.js
src/constants.js
src/entry.js

Implementing this to hide baselines tab from add system modal.

Add cookie to enable and disable experimental features

---

src/SmartComponents/modules/__tests__/reducer-test.js
src/SmartComponents/modules/helpers.js
src/SmartComponents/modules/reducers.js

Also added reducer tests to 100%

Split pure functions in reducer to helpers file

---

src/SmartComponents/BaselinesTable/redux/__tests__/baselinesTableReducer.fixtures.js
src/SmartComponents/BaselinesTable/redux/baselinesTableReducer.js
src/api.js

To match what's returned by the api in system-baselines-backend/pr/10

Update whats returned from the api response

---

profiles/local-frontend-and-api.js
profiles/local-frontend.js
src/App.js

This changes `SECTION`. It also registers the left-hand nav which
makes things work in CI.

use `rhel`, not `apps`

---

package-lock.json
package.json
src/SmartComponents/BaselinesTable/redux/__tests__/baselinesTableReducer.fixtures.js
src/SmartComponents/BaselinesTable/redux/helpers.js
src/SmartComponents/DriftPage/DriftTable/DriftTable.js

Fix date time stamp of baselines in comparison table. Fix date time stamp of baselines in baseline list

Fix date/time stamps

---

src/SmartComponents/BaselinesPage/BaselinesPage.js
src/SmartComponents/BaselinesTable/BaselineTableKebab/BaselineTableKebab.js
src/SmartComponents/BaselinesTable/BaselinesTable.js
src/SmartComponents/BaselinesTable/redux/__tests__/baselinesTableReducer-tests.js
src/SmartComponents/BaselinesTable/redux/__tests__/baselinesTableReducer.fixtures.js
src/SmartComponents/BaselinesTable/redux/baselinesTableReducer.js
src/SmartComponents/BaselinesTable/redux/helpers.js
src/api.js

This adds an empty state on search within the table in addition.

Fix empty state appearing if no baselines returned from search

---

src/SmartComponents/BaselinesPage/EditBaseline/FactKebab/FactKebab.js
src/SmartComponents/BaselinesPage/EditBaseline/FactModal/FactModal.js
src/SmartComponents/BaselinesPage/EditBaseline/helpers.js
src/SmartComponents/BaselinesTable/redux/helpers.js

Adding new subfact replaces existing subfact
Updating sub-fact value results in all other sub-facts disappearing
Actions on facts/categories is not matching after fact/sub-fact editing
Editing category deletes sub-facts
Delete facts functionality doesn't work properly

Fixed bugs with editing facts

---

src/SmartComponents/DriftPage/SearchBar/SearchBar.js

Fixes:
Filter value is kept when adding a baseline to a comparison but not showing in the box

Makes fact filter on comparison table persistent

---

src/SmartComponents/BaselinesPage/CreateBaselineModal/CreateBaselineModal.js

Fixes 'Creating a baseline via a baseline and then going back to the create baseline modal and creating a baseline without selection incorrectly creates new baseline'

Fixes issue with not clearing selected baselines and systems

---

src/App.scss
src/SmartComponents/BaselinesPage/CreateBaselineModal/CreateBaselineModal.js

Also increased the size of the modal to show more than 1 system

Temporarily block submit baseline button when no data is selected

---

src/App.scss
src/SmartComponents/AddSystemModal/AddSystemModal.js
src/SmartComponents/DriftPage/ActionKebab/ActionKebab.js
src/SmartComponents/DriftPage/DriftTable/DriftTable.js
src/SmartComponents/DriftPage/__tests__/DriftPage.tests.js
src/SmartComponents/DriftPage/__tests__/__snapshots__/DriftPage.tests.js.snap
src/SmartComponents/HistoricalProfilesDropdown/FetchHistoricalProfilesButton/FetchHistoricalProfilesButton.js
src/SmartComponents/HistoricalProfilesDropdown/HistoricalProfilesCheckbox/HistoricalProfilesCheckbox.js
src/SmartComponents/HistoricalProfilesDropdown/HistoricalProfilesDropdown.js
src/SmartComponents/HistoricalProfilesDropdown/redux/reducers.js

Fixes remove button on historical profiles and correctly selects and deselects historical profiles in dropdown.

Fix bugs with historical system profiles

---

src/SmartComponents/modules/helpers.js
src/SmartComponents/modules/reducers.js

Also added updated time stamp to CSV to differentiate between systems and historical system profiles

Add historical system profiles to comparison csv export

---

package.json
src/SmartComponents/DriftPage/DriftTable/DriftTable.js
src/SmartComponents/DriftPage/DriftTable/__tests__/DriftTable.tests.js
src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap
src/SmartComponents/DriftPage/__tests__/__snapshots__/DriftPage.tests.js.snap
src/SmartComponents/modules/__tests__/reducer.fixtures.js

This includes a bit of re-factor towards having a single source of
truth for the master sorted system data.

Fixes data and header alignment with profiles

---

src/SmartComponents/AddSystemModal/AddSystemModal.js
src/SmartComponents/BaselinesPage/CreateBaselineModal/__tests__/CreateBaselineModal.tests.js
src/SmartComponents/DriftPage/DriftTable/DriftTable.js
src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap
src/SmartComponents/DriftPage/__tests__/__snapshots__/DriftPage.tests.js.snap
src/SmartComponents/HistoricalProfilesDropdown/FetchHistoricalProfilesButton/FetchHistoricalProfilesButton.js
src/SmartComponents/HistoricalProfilesDropdown/FetchHistoricalProfilesButton/__tests__/FetchHistoricalProfilesButton.tests.js
src/SmartComponents/HistoricalProfilesDropdown/FetchHistoricalProfilesButton/__tests__/__snapshots__/FetchHistoricalProfilesButton.tests.js.snap
src/SmartComponents/HistoricalProfilesDropdown/HistoricalProfilesCheckbox/HistoricalProfilesCheckbox.js
src/SmartComponents/HistoricalProfilesDropdown/HistoricalProfilesDropdown.js
src/SmartComponents/HistoricalProfilesDropdown/__tests__/HistoricalProfilesDropdown.tests.js
src/SmartComponents/HistoricalProfilesDropdown/__tests__/__snapshots__/HistoricalProfilesDropdown.tests.js.snap
src/SmartComponents/SystemsTable/SystemsTable.js
src/SmartComponents/SystemsTable/reducers.js

Still need tests and possibly a rebase...

Add historical profile dropdown to system select table

---

src/SmartComponents/BaselinesPage/ExportCSVButton/ExportCSVButton.js
src/SmartComponents/BaselinesPage/__tests__/__snapshots__/BaselinesPage.tests.js.snap

We refactored the baselinesTableState with checkboxTable and radioTable redux states but forgot to update the ExportCSVButton Component with the correct state.

Update baseline list export

---

src/App.scss
src/SmartComponents/BaselinesPage/EditBaseline/DeleteFactModal/DeleteFactModal.js
src/SmartComponents/BaselinesPage/EditBaseline/EditBaselineKebab/EditBaselineKebab.js
src/SmartComponents/BaselinesPage/EditBaseline/FactKebab/FactKebab.js
src/SmartComponents/DriftPage/AddSystemButton/AddSystemButton.js
src/SmartComponents/DriftPage/AddSystemButton/__tests__/__snapshots__/AddSystemButton.test.js.snap
src/SmartComponents/DriftPage/DriftTable/DriftTable.js
src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap
src/SmartComponents/DriftPage/__tests__/__snapshots__/DriftPage.tests.js.snap

Fixes:
- Change button to 'Add to comparison' in homepage
- Add 16px space for caret icon and category name in Edit baselines
- Fact and State should be aligned to the top of the cell
- Add bold to facts and categories in 'Delete facts' error message

Fixed some UI styling issues

---

src/App.scss
src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap
src/SmartComponents/HistoricalProfilesDropdown/HistoricalProfilesDropdown.js
src/SmartComponents/HistoricalProfilesDropdown/__tests__/__snapshots__/HistoricalProfilesDropdown.tests.js.snap

Also fixes spacing issues on dropdown scroll and padding all around dropdown

Add header to HSP dropdown for systems

---

src/App.scss
src/SmartComponents/BaselinesPage/ExportCSVButton/ExportCSVButton.js
src/SmartComponents/BaselinesPage/__tests__/__snapshots__/BaselinesPage.tests.js.snap
src/SmartComponents/BaselinesTable/BaselinesToolbar/__test__/__snapshots__/BaselinesToolbar.test.js.snap
src/SmartComponents/BaselinesTable/__tests__/__snapshots__/BaselinesTable.tests.js.snap
src/SmartComponents/DriftPage/AddSystemButton/AddSystemButton.js
src/SmartComponents/DriftPage/AddSystemButton/__tests__/__snapshots__/AddSystemButton.test.js.snap
src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap
src/SmartComponents/DriftPage/ExportCSVButton/ExportCSVButton.js
src/SmartComponents/DriftPage/FilterDropDown/FilterDropDown.js
src/SmartComponents/DriftPage/__tests__/__snapshots__/DriftPage.tests.js.snap

Fixes:
- 1625-fix-spacing-in-toolbar-for-comparison
- 1650-fix-gap-between-view-and-add-to-comparison-when-no-filter-is-selected

Fix toolbar spacing issues

---

src/App.scss
src/SmartComponents/DriftPage/FilterDropDown/FilterDropDown.js
src/SmartComponents/DriftPage/__tests__/__snapshots__/DriftPage.tests.js.snap

Update wraps the checkboxes in a <DropdownItem> which adds PF CSS rules for consistency. Also fixes weird wrapping when all filters are deselected.

Change filter dropdown to <DropdownItem> in menu

---

src/SmartComponents/DriftPage/DriftTable/DriftTable.js

Build a comparison with at least one baseline:
- The first baseline in the comparison gets set as the reference (look for the star to be highlighted on the baseline header)
- If you choose something else as a reference, it will de-reference that baseline. De-referencing your second choice of a reference will result in no references being set
Build a comparison with anything but a baseline:
- If you build your comparison without the baseline, and then add a baseline to the comparison, the baseline will be set at the default reference.
- If you build your comparison without the baseline, then choose one of your systems/HSPs as a reference, then dereference it, and then add a baseline, that baseline will not be set as the default reference

First baseline in comparison gets automatic reference set

---

src/SmartComponents/BaselinesPage/EditBaseline/FactModal/FactModal.js
src/SmartComponents/BaselinesPage/EditBaseline/FactModal/__tests__/FactModal.tests.js
src/SmartComponents/BaselinesPage/EditBaseline/FactModal/__tests__/__snapshots__/FactModal.tests.js.snap
src/SmartComponents/BaselinesPage/EditBaseline/redux/reducers.js

To test, try to create a new fact with the same name as an existing fact.

Fix text input error alert in fact modal

---

src/App.js
src/SmartComponents/BaselinesPage/BaselinesPage.js
src/SmartComponents/BaselinesPage/CreateBaselineModal/CreateBaselineModal.js
src/SmartComponents/BaselinesPage/__tests__/__snapshots__/BaselinesPage.tests.js.snap
src/SmartComponents/BaselinesTable/BaselinesTable.js

Updated so rbac permission checking is only done in beta.

Fix broken rbac permissions

---

src/SmartComponents/AddSystemModal/AddSystemModal.js
src/SmartComponents/DriftPage/DriftPage.js
src/SmartComponents/DriftPage/DriftTable/DriftTable.js

I wasn't passing props from the app level all the way down to Baselines Table through Add System Modal. Two different components build Baselines Table and I was only passing it down one of those paths.

Fix more issues with rbac

---

src/SmartComponents/BaselinesPage/EditBaseline/FactModal/FactModal.js
src/SmartComponents/BaselinesPage/EditBaseline/FactModal/__tests__/__snapshots__/FactModal.tests.js.snap

Spacing between fact and value text input areas are decreased.

Fix spacing on Fact Modal

---

src/App.scss
src/SmartComponents/BaselinesPage/EditBaseline/FactModal/FactModal.js
src/SmartComponents/BaselinesPage/EditBaseline/FactModal/__tests__/__snapshots__/FactModal.tests.js.snap

Also fixed spacing of form groups in edit baseline name modal and edit/add fact modals

Fix spacing in Edit Baseline Name modal under title

---

src/SmartComponents/DriftPage/DriftPage.js
src/SmartComponents/DriftPage/DriftToolbar/DriftToolbar.js
src/SmartComponents/DriftPage/DriftToolbar/__tests__/DriftToolbar.tests.js
src/SmartComponents/DriftPage/DriftToolbar/__tests__/__snapshots__/DriftToolbar.tests.js.snap
src/SmartComponents/DriftPage/__tests__/DriftPage.tests.js
src/SmartComponents/DriftPage/__tests__/__snapshots__/DriftPage.tests.js.snap

To test, just make sure that all of the functionality of the drift comparison toolbar works as expected.
- Filtering
- State filtering
- Add to comparison
- Export to CSV
- Clear all comparisons
- Pagination
- Filter chips
- Clear filters

Create Drift Toolbar component

---

src/SmartComponents/BaselinesTable/BaselinesTable.js
src/SmartComponents/BaselinesTable/__tests__/__snapshots__/BaselinesTable.tests.js.snap

This fix should allow you to load inventory table. Make sure to check baseline table in add system modal.

Fix error on header of baseline table in add system modal

---

src/SmartComponents/DriftPage/DriftTable/ComparisonHeader/ComparisonHeader.js
src/SmartComponents/DriftPage/DriftTable/ComparisonHeader/__tests__/ComparisonHeader.tests.js
src/SmartComponents/DriftPage/DriftTable/ComparisonHeader/__tests__/__snapshots__/ComparisonHeader.tests.js.snap
src/SmartComponents/DriftPage/DriftTable/DriftTable.js
src/SmartComponents/DriftPage/DriftTable/__tests__/DriftTable.tests.js
src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap
src/SmartComponents/DriftPage/__tests__/__snapshots__/DriftPage.tests.js.snap

Header in comparison table should act the same as it did before.

Break comparison header into its own component

---

src/App.scss
src/SmartComponents/BaselinesPage/EditBaseline/FactModal/FactModal.js
src/SmartComponents/BaselinesPage/EditBaseline/FactModal/__tests__/__snapshots__/FactModal.tests.js.snap

Fix spacing in fact modal under category checkbox

---

src/SmartComponents/DriftPage/DriftTable/ComparisonHeader/ComparisonHeader.js
src/SmartComponents/DriftPage/DriftTable/ComparisonHeader/__tests__/__snapshots__/ComparisonHeader.tests.js.snap
src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap
src/SmartComponents/DriftPage/__tests__/__snapshots__/DriftPage.tests.js.snap

Adding ouia attributes to the Fact sorting header on Comparison table

add ouia attributes to fact name sorting

---

src/SmartComponents/modules/helpers.js

https://issues.redhat.com/browse/DRFT-129

DRFT-129 Implement tooltips for INCOMPLETE_DATA_OBFUSCATED fact state

---

src/SmartComponents/DriftPage/DriftTable/DriftTable.js
src/SmartComponents/DriftPage/DriftTable/__tests__/DriftTable.tests.js
src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap
src/SmartComponents/modules/__tests__/helpers-tests.js
src/SmartComponents/modules/__tests__/multiFact-filter-fixtures.js
src/SmartComponents/modules/__tests__/reducer.fixtures.js
src/SmartComponents/modules/helpers.js
src/SmartComponents/modules/reducers.js
src/api.js
src/constants.js

This PR adds the ability to read multiple values for facts as part of a category. This works for filtering, sorting and exporting as CSV.
To test:
- Test that you can expand sub-facts of a category that have multiple values
- Test that fact filters don't affect multi-values
- Test that a fact filter that matches that of a fact with multi-values shows all values of that fact
- Test that fact sorting only affects the categories and sub-facts and not the multi-facts
- Test that state sorting affects multi-facts (remember that state sort takes precendence over fact sort)
- Test that all the crazy things you can do don't break the app :)

DRFT-102 Read multi-value facts in comparison table

---

src/SmartComponents/BaselinesPage/CreateBaselineButton/CreateBaselineButton.js
src/SmartComponents/BaselinesPage/CreateBaselineButton/__tests__/__snapshots__/CreateBaselineButton.tests.js.snap
src/SmartComponents/BaselinesPage/CreateBaselineModal/CreateBaselineModal.js
src/SmartComponents/BaselinesPage/CreateBaselineModal/__tests__/__snapshots__/CreateBaselineModal.tests.js.snap
src/SmartComponents/BaselinesPage/EditBaseline/EditBaseline.js
src/SmartComponents/BaselinesPage/EditBaseline/__tests__/__snapshots__/EditBaseline.tests.js.snap
src/SmartComponents/BaselinesPage/__tests__/__snapshots__/BaselinesPage.tests.js.snap
src/SmartComponents/BaselinesTable/BaselinesToolbar/__test__/__snapshots__/BaselinesToolbar.test.js.snap
src/SmartComponents/BaselinesTable/__tests__/__snapshots__/BaselinesTable.tests.js.snap
src/SmartComponents/DriftPage/ActionKebab/ActionKebab.js
src/SmartComponents/DriftPage/__tests__/__snapshots__/DriftPage.tests.js.snap

ouia attributes for:
- Action kebab (both views)
- Edit baseline Breadcrumb
- Edit baseline Edit name button
- Create baseline radios (NOT table radios)
- Create baseline modal footer buttons

[DRFT-147] baselines view ouia main components

---

src/SmartComponents/DriftPage/DriftPage.js
src/SmartComponents/DriftPage/DriftTable/ComparisonHeader/ComparisonHeader.js
src/SmartComponents/DriftPage/DriftTable/ComparisonHeader/__tests__/__snapshots__/ComparisonHeader.tests.js.snap
src/SmartComponents/DriftPage/DriftTable/DriftTable.js
src/SmartComponents/DriftPage/DriftTable/ReferenceSelector/ReferenceSelector.js
src/SmartComponents/DriftPage/DriftTable/ReferenceSelector/__tests__/__snapshots__/ReferenceSelector.tests.js.snap
src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap
src/SmartComponents/DriftPage/DriftToolbar/DriftToolbar.js
src/SmartComponents/DriftPage/DriftToolbar/__tests__/__snapshots__/DriftToolbar.tests.js.snap
src/SmartComponents/DriftPage/__tests__/__snapshots__/DriftPage.tests.js.snap
src/SmartComponents/HistoricalProfilesPopover/HistoricalProfilesPopover.js
src/SmartComponents/HistoricalProfilesPopover/__tests__/__snapshots__/HistoricalProfilesPopover.tests.js.snap
src/SmartComponents/Pagination/Pagination.js

- table row, header row
- pagination (top lvl element only)
- category information on subfacts
- expand category button
- drift header cells

[DRFT-147] ouia for comparison view

---

src/SmartComponents/BaselinesPage/EditBaseline/DeleteFactModal/DeleteFactModal.js
src/SmartComponents/BaselinesPage/EditBaseline/FactModal/FactModal.js
src/SmartComponents/BaselinesPage/EditBaseline/FactModal/__tests__/__snapshots__/FactModal.tests.js.snap

- Add and Delete modals for baseline facts
- TextInput elements
- buttons

[DRFT-147] baseline fact modal

---

src/SmartComponents/BaselinesPage/EditBaseline/AddFactButton/AddFactButton.js
src/SmartComponents/BaselinesPage/EditBaseline/EditBaseline.js
src/SmartComponents/BaselinesPage/EditBaseline/EditBaselineKebab/EditBaselineKebab.js
src/SmartComponents/BaselinesPage/EditBaseline/EditBaselineToolbar/EditBaselineToolbar.js
src/SmartComponents/BaselinesPage/EditBaseline/EditBaselineToolbar/__tests__/__snapshots__/EditBaselineToolbar.tests.js.snap
src/SmartComponents/BaselinesPage/EditBaseline/FactKebab/FactKebab.js
src/SmartComponents/BaselinesPage/EditBaseline/__tests__/__snapshots__/EditBaseline.tests.js.snap

- Add fact or category button
- Edit Baseline kebab
- Edit baseline table row, header row
- _category_ attribute for subfacts
- bulk selector - but only the Dropdown element

[DRFT-147] ouia for baseline view

---

src/SmartComponents/AddSystemModal/AddSystemModal.js
src/SmartComponents/AddSystemModal/__tests__/__snapshots__/AddSystemModal.tests.js.snap
src/SmartComponents/BaselinesPage/__tests__/__snapshots__/BaselinesPage.tests.js.snap
src/SmartComponents/BaselinesTable/BaselinesToolbar/BaselinesToolbar.js
src/SmartComponents/BaselinesTable/BaselinesToolbar/__test__/__snapshots__/BaselinesToolbar.test.js.snap
src/SmartComponents/BaselinesTable/__tests__/__snapshots__/BaselinesTable.tests.js.snap
src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap
src/SmartComponents/DriftPage/__tests__/__snapshots__/DriftPage.tests.js.snap
src/SmartComponents/SystemsTable/SystemsTable.js
src/SmartComponents/SystemsTable/__tests__/__snapshots__/SystemsTable.tests.js.snap

add to comparison modal
- modal buttons
- tab buttons
- baseline table toolbar
- top-lvl table elements

ouia for add to comparison modal

---

package-lock.json
package.json
src/store/index.js

When returning to app in chrome 2 the code was already run parsed and store initialized. The registry must be re-initialized to properly bootstrap the app.
(also updated the webpack config to stable version)
cc @johnsonm325

Fix store initialized issue

---

src/SmartComponents/BaselinesPage/EditBaseline/EditBaseline.js
src/SmartComponents/BaselinesTable/BaselinesTable.js
src/SmartComponents/BaselinesTable/__tests__/__snapshots__/BaselinesTable.tests.js.snap

To reproduce:
1. Edit click on kebab dropdown
- Go to baselines list
- Click kebab on baseline row
- Click edit
This will not do anything.
2. Edit category name
- Go to a baseline
- Edit a category
- Change the name of the category
- Click "Save"
This will not load the baseline details properly

Fixes editing category name and edit click on kebab dropdown

---

config/prod.webpack.config.js

Fix beta deployment, by including BUILD_BETA env

---

package-lock.json
package.json

fixes: https://issues.redhat.com/browse/RHCLOUD-13395
cc @johnsonm325 @msager27

Update webpack config.

---

src/store/reducers.js

To repro:
- Select some systems for a baseline
- Click Name and/or Last seen
The arrows change direction, but the table isn't sorted
This PR temporarily disables sorting until we can fix.

[DRFT-322] Disable sorting notifications

---

package-lock.json
package.json
src/SmartComponents/AddSystemModal/__tests__/__snapshots__/AddSystemModal.tests.js.snap
src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaseline/__tests__/__snapshots__/EditBaseline.tests.js.snap
src/SmartComponents/BaselinesTable/__tests__/__snapshots__/BaselinesTable.tests.js.snap
src/SmartComponents/SystemsTable/NotificationsSystemsTable.js
src/SmartComponents/SystemsTable/SystemsTable.js
src/SmartComponents/SystemsTable/__tests__/__snapshots__/SystemsTable.tests.js.snap

Effectively updates sanitize-html dependency to 2.3.2

[DRFT-240] Update frontend-components to 3.1.11

---

.babelrc

Did a full `npm update` to make sure `browserslist` was on version 4.16.6 to handle CVE.

[DRFT-353] Update packages for browserslist dependency

---

src/App.js

[DRFT] Fix typo in checking hsp read permissions

---

src/SmartComponents/DriftPage/DriftPage.js
src/SmartComponents/DriftPage/__tests__/DriftPage.tests.js

To repro:
Select 1 or more systems for comparison
Select Comparison from the left panel.  The comparison table is still displayed.  However, the url params are cleared.
This PR correctly sets the url with the params.

[DRFT-364] Fixes url clear on side nav Comparison click

---

src/SmartComponents/AddSystemModal/AddSystemModal.js
src/SmartComponents/AddSystemModal/__tests__/AddSystemModal.tests.js
src/SmartComponents/AddSystemModal/redux/__tests__/addSystemModalReducer.fixtures.js
src/store/__tests__/reducer-test.js
src/store/reducers.js

To repro:
- navigate to Add to comparison
- check a system on page 1
- change to next page (page 2)
- check a system
- open systems basket, uncheck all systems in it, click X button on the popover
The system from page 1 is still in the basket.
The Submit button is disabled
Navigating to page 1, the system is not selected (although it's still in the basket)

[DRFT-362] Deselect system from basket on different inventory page

---

src/SmartComponents/AddSystemModal/SelectedBasket/SelectedBasket.js
src/SmartComponents/AddSystemModal/SelectedBasket/__tests__/__snapshots__/SelectedBasket.tests.js.snap
src/SmartComponents/AddSystemModal/__tests__/__snapshots__/AddSystemModal.tests.js.snap

Persistent scroll bar in Selected Basket is gone and the minWidth and maxHeight have been increased.
To test:
- Go to Comparison
- Click "Add system" button
- Add varying numbers of systems and click the `Selected (x)` in the top right of the modal
You should see the basket adjust.

[DRFT 374] Fix selected basket sizing and scroll bar

---

scripts/release-prod
scripts/release-qa

Before, if you ran a release script before committing changes, you would lose everything. This properly stashes them to avoid loss of work.

Change release scripts to stash changes

---

README.md

Final fix to readme

---

src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaselinePage.js
src/SmartComponents/BaselinesPage/EditBaselinePage/SystemNotification/DeleteNotificationModal/DeleteNotificationModal.js
src/SmartComponents/BaselinesPage/EditBaselinePage/SystemNotification/SystemKebab/SystemKebab.js
src/SmartComponents/BaselinesPage/EditBaselinePage/SystemNotification/SystemNotification.js
src/SmartComponents/BaselinesPage/EditBaselinePage/SystemNotification/__tests__/__snapshots__/SystemNotification.tests.js.snap
src/SmartComponents/SystemsTable/NotificationsSystemsTable.js

Made the changes on naming inconsistencies in single baseline tab.

[DRFT-367] Update wording for notifications

---

src/SmartComponents/AddSystemModal/AddSystemModal.js
src/SmartComponents/AddSystemModal/redux/__tests__/addSystemModalReducer-tests.js
src/SmartComponents/AddSystemModal/redux/__tests__/addSystemModalReducer.fixtures.js
src/SmartComponents/AddSystemModal/redux/helpers.js
src/SmartComponents/DriftTooltip/DriftTooltip.js
src/SmartComponents/DriftTooltip/__tests__/DriftTooltip.tests.js
src/SmartComponents/DriftTooltip/__tests__/__snapshots__/DriftTooltip.tests.js.snap
src/SmartComponents/helpers.js
src/store/__tests__/reducer-test.js

Systems, baselines and hsps added to the selected basket should each have an icon with a tooltip noting whether it is a 'System', 'Baseline' or 'Historical profile'.

[DRFT-375] Add tooltips for icons in selected basket

---

src/App.scss
src/SmartComponents/DriftPage/DriftTable/ComparisonHeader/ComparisonHeader.js
src/SmartComponents/DriftPage/DriftTable/ComparisonHeader/__tests__/__snapshots__/ComparisonHeader.tests.js.snap
src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap

To repro:
Create a comparison
The icons next to the names of the systems/baselines/hsps in the table header are aligned with the bottom of the names. This PR aligns them in the center.

[DRFT-563] Align icons in system header to system name

---

src/App.scss
src/store/reducers.js

To repro:
Open inventory table
Find a system with hsps and select at least 1 hsp from the popover
The badge and hsp icon are slightly misaligned. This PR properly aligns them.

[DRFT-559] Align HSP icon and badge in inventory table

---

src/App.scss
src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaseline/EditBaseline.js
src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaseline/__tests__/__snapshots__/EditBaseline.tests.js.snap
src/SmartComponents/BaselinesTable/BaselineTableKebab/BaselineTableKebab.js
src/SmartComponents/BaselinesTable/BaselinesTable.js
src/SmartComponents/BaselinesTable/__tests__/__snapshots__/BaselinesTable.tests.js.snap

Before, the kebab in the baselines table and the kebab in the baseline details table were not vertically aligned across the row. This PR sets the vertical alignment for each cell in the row to the middle.

[DRFT-565] Align kebab in table for baselines and baseline details

---

README.md

Adds USE_CLOUD=true to insights-proxy commands in README

---

README.md
profiles/local-frontend-and-ephemeral-cluster.js

[DRFT-767] Automate Clowder dev-setup

---

README.md
profiles/local-frontend-and-ephemeral-cluster.js

Added how to run with clowder section and profiles file

---

src/App.scss
src/SmartComponents/AddSystemModal/__tests__/__snapshots__/AddSystemModal.tests.js.snap
src/SmartComponents/SystemsTable/SystemsTable.js
src/SmartComponents/SystemsTable/__tests__/__snapshots__/SystemsTable.tests.js.snap
src/store/reducers.js

Before, the content in the Tags column of the inventory table were misaligned with the center of the table rows. This PR centers the content in the Tags column with the rest of the row and ensures all row content is centered.

[DRFT-570] Align cell content in inventory table

---

src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaseline/EditBaseline.js
src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaseline/__tests__/EditBaseline.tests.js
src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaseline/__tests__/__snapshots__/EditBaseline.tests.js.snap
src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaseline/__tests__/helpers.fixtures.js
src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaseline/__tests__/helpers.tests.js
src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaseline/helpers.js

Two similar issues.  First:
- Create baseline
- Add fact name: f1
- Add category name: f1
- Attempt to add a subfact for category name: f1. This hangs, so cancel.
- Rename fact name: f1 to name: f2.  This has the side effect of category name: f1 being deleted.
Second:
- Create baseline
- Add fact name: f1
- Add category name: f1
- Attempt to rename category name: f1 to name: c1.  This hangs, so cancel.
- Rename fact name: f1 to name: f2.  This has the side effect of category name: f1 being deleted.
This PR should allow facts/categories/sub facts to be added, edited and deleted as normal.
Also fixed an issue with the bulk select.
To reproduce:
- create a category and a fact (names don't matter)
- click checkbox in bulk selector and it should show that only 1 is selected
This PR fixes it so …

[DRFT-584] Fix issues with add/delete/edit facts

---

scripts/release-prod
scripts/release-qa

https://issues.redhat.com/browse/DRFT-802

[DRFT-802] Detects names of remotes when deploying

---

src/SmartComponents/BaselinesPage/BaselinesPage.js
src/SmartComponents/BaselinesPage/__tests__/__snapshots__/BaselinesPage.tests.js.snap
src/SmartComponents/BaselinesTable/BaselinesTable.js
src/SmartComponents/BaselinesTable/BaselinesToolbar/__test__/__snapshots__/BaselinesToolbar.test.js.snap
src/SmartComponents/BaselinesTable/NotificationDetails/NotificationDetails.js
src/SmartComponents/BaselinesTable/__tests__/BaselinesTable.tests.js
src/SmartComponents/BaselinesTable/__tests__/__snapshots__/BaselinesTable.tests.js.snap
src/SmartComponents/BaselinesTable/redux/__tests__/baselinesTableReducer.fixtures.js
src/SmartComponents/BaselinesTable/redux/helpers.js

This PR adds another column to the baselines list page that includes a count of associated systems for each baseline. To test, add associated systems to baselines in your list and revisit the baselines page to ensure they have updated.
This PR must be merged after: https://github.com/RedHatInsights/system-baseline-backend/pull/221
They can be tested simultaneously, or after the backend change has been merged.

[DRFT-809] Add count of associated systems to baselines list

---

src/SmartComponents/modules/__tests__/helpers-tests.js
src/SmartComponents/modules/__tests__/reducer.fixtures.js
src/SmartComponents/modules/helpers.js

Previously, if you ran a comparison with a system that had multi-value facts, you wouldn't be able to export to JSON. This PR fixes that.

[DRFT-828] Update JSON export to handle multivalues

---

src/SmartComponents/AddSystemModal/AddSystemModal.js
src/SmartComponents/AddSystemModal/SelectedBasket/SelectedBasket.js
src/SmartComponents/AddSystemModal/__tests__/AddSystemModal.tests.js
src/SmartComponents/AddSystemModal/__tests__/__snapshots__/AddSystemModal.tests.js.snap
src/SmartComponents/AddSystemModal/redux/helpers.js
src/SmartComponents/DriftPage/DriftTable/DriftTable.js
src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap
src/SmartComponents/DriftPage/__tests__/__snapshots__/DriftPage.tests.js.snap

Multiple issues found with selected basket and add system modal:
- When comparison is run with any number of systems and/or baselines, go back to add system modal and remove all selections. An error is thrown.
- When a comparison is run with any number of baselines, go back to add system modal and remove at least one baseline and cancel selection. If you go back to the add system modal, the baseline will be deselected, but it's still in the selected basket and is still a part of the comparison
- When a comparison is run with any number of systems and/or baselines, set a reference and go back to add system modal and remove the reference and re-run the comparison. An error is thrown saying that the reference was not found.
This PR fixes all of these issues.
- …

[DRFT-935] Fix selected basket selection issues

---

src/SmartComponents/AddSystemModal/SelectedBasket/SelectedBasket.js
src/SmartComponents/AddSystemModal/SelectedBasket/__tests__/SelectedBasket.tests.js
src/SmartComponents/AddSystemModal/SelectedBasket/__tests__/__snapshots__/SelectedBasket.tests.js.snap
src/SmartComponents/AddSystemModal/__tests__/__snapshots__/AddSystemModal.tests.js.snap
src/SmartComponents/BaselinesTable/BaselinesToolbar/__test__/__snapshots__/BaselinesToolbar.test.js.snap
src/SmartComponents/BaselinesTable/__tests__/__snapshots__/BaselinesTable.tests.js.snap
src/SmartComponents/BaselinesTable/redux/__tests__/baselinesTableReducer.fixtures.js

When no changes have been made to the selected basket, the apply changes button should be disabled.

[DRFT-366] Disable Apply Changes button when no change made in basket

---

package-lock.json
src/SmartComponents/DriftPage/DriftPage.js
src/SmartComponents/DriftPage/DriftTable/DriftTable.js
src/SmartComponents/DriftPage/DriftTable/DriftTableRow/DriftTableRow.js
src/SmartComponents/DriftPage/DriftTable/DriftTableRow/RowFact.js
src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap

This is a refactor of the drift table. I've moved some of the logic of the table rows into other components to simplify the DriftTable component. Now, the DriftTable component only handles the table, while the rows are rendered from the DriftTableRows component and the fact cells are rendered via the RowFact component.
The output should look and act the same.

Refactor Drift table

---

.travis/custom_release.sh

Before, a merge to master released directly to ci-beta and ci-stable. And a push to qa had to happen seperately.
Now, this PR updates the custom release script so that a merge to master goes to qa-beta and qa-stable. While ci and qa will no longer be used, qa also merges to stage, so this change effectly takes a push to master directly to stage. We will still utilize our prod release script to push from stage to prod.

Update custom release script to go master -> qa

---

drift-frontend-manifest.txt

Update drift-frontend manifest

---

src/SmartComponents/DriftPage/DriftTable/DriftTable.js

To reproduce
- In stage, open add system modal
- Select systems/baselines for a comparison
- Click "Submit" button
This should lead to a blank page. This PR fixes that.

[DRFT-1112] Fix blank page on comparison

---

package-lock.json
package.json

This update allows Baselines text filter to accept letters. The filter should work normally.

[DRFT-1148] Update FEC version

---

src/SmartComponents/SystemsTable/NotificationsSystemsTable.js
src/SmartComponents/SystemsTable/__tests__/__snapshots__/NotificationsSystemsTable.tests.js.snap

To reproduce
- navigate to a baseline
- click "Associated systems" tab
- click the kebab in the toolbar
The kebab dropdown should be empty. This PR restores the delete associated system(s) functionality.

[DRFT-1181] Fix delete assoc. sys. kebab

---

package.json
src/SmartComponents/AddSystemModal/__tests__/__snapshots__/AddSystemModal.tests.js.snap
src/SmartComponents/BaselinesPage/DeleteBaselinesModal/DeleteBaselinesModal.js
src/SmartComponents/BaselinesPage/DeleteBaselinesModal/__tests__/__snapshots__/DeleteBaselinesModal.tests.js.snap
src/SmartComponents/BaselinesPage/__tests__/__snapshots__/BaselinesPage.tests.js.snap
src/SmartComponents/BaselinesTable/BaselinesToolbar/BaselinesToolbar.js
src/SmartComponents/BaselinesTable/BaselinesToolbar/__test__/__snapshots__/BaselinesToolbar.test.js.snap

resolves https://issues.redhat.com/browse/DRFT-842
I also added number indicating how many baselines will be deleted to the Modal, although this was not requested in the ticket. Let me know what you think about it.

feat(DeleteBaselinesModal): DRFT-842 - Update message when deleting baseline

---

package.json

This PR moves the jest.test to scripts.test where it should have been.

Fix jest test script in package.json

---

src/App.scss
src/SmartComponents/BaselinesTable/BaselinesToolbar/__test__/__snapshots__/BaselinesToolbar.test.js.snap
src/SmartComponents/BaselinesTable/redux/__tests__/baselinesTableReducer.fixtures.js

This code fixes the Table overlap with the pagination, etc.
[DRFT-1209](https://issues.redhat.com/browse/DRFT-1209)
Before:
After:

[DRFT-1209] Fix pagination overlap

---

src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaselinePage.js
src/SmartComponents/DriftPage/DriftPage.js

fix: ESSNTL-3923 - Pass store to Main component

---

src/SmartComponents/BaselinesTable/BaselinesTable.js
src/SmartComponents/BaselinesTable/BaselinesToolbar/__test__/__snapshots__/BaselinesToolbar.test.js.snap
src/SmartComponents/BaselinesTable/redux/__tests__/baselinesTableReducer.fixtures.js

To repro:
- go to baselines page
- change per page to any other amount
- sort on a column
This fails, but this PR fixes that.

[DRFT-1218] Fix sorting after updatePagination

---

src/SmartComponents/BaselinesPage/EditBaselinePage/DeleteFactModal/DeleteFactModal.js
src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaselineKebab/EditBaselineKebab.js
src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaselineToolbar/__tests__/__snapshots__/EditBaselineToolbar.tests.js.snap

Adds 'selected' on delete fact modals (https://issues.redhat.com/browse/DRFT-842)
The baseline modal was already updated in https://github.com/RedHatInsights/drift-frontend/pull/601

fix(DeleteFactModal): DRFT842 - Update message when deleting fact

---

src/SmartComponents/BaselinesPage/EditBaselinePage/DeleteFactModal/DeleteFactModal.js
src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaseline/__tests__/__snapshots__/EditBaseline.tests.js.snap
src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaselineKebab/EditBaselineKebab.js
src/SmartComponents/BaselinesPage/EditBaselinePage/FactKebab/FactKebab.js

The previous fix for this card only fixed the messages for selected facts to be deleted. This PR fixes selected categories to be deleted. Also, when at least 1 fact and 1 category have been selected for deletion, we generalize the message to "Delete selected facts".
To thoroughly test, try selected multiple facts and categories and deleting via the kebab in the toolbar, and also try deleting individual facts and categories via the kebab on the row of the table.

[DRFT-842] Fix delete message for categories

---

src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaselineNameModal/EditBaselineNameModal.js
src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaselinePage.js

This PR fixes the baseline name notification not showing up after successful change.

[DRFT-371] Fix baseline name notification

---

src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaselineNameModal/EditBaselineNameModal.js
src/constants.js

Successful toast alerts should auto dismiss.

[DRFT-371] Add autoDismiss to success alerts

---

config/setupTests.js
src/App.js
src/SmartComponents/AddSystemModal/AddSystemModal.js
src/SmartComponents/AddSystemModal/SelectedBasket/__tests__/__snapshots__/SelectedBasket.tests.js.snap
src/SmartComponents/AddSystemModal/__tests__/AddSystemModal.tests.js
src/SmartComponents/AddSystemModal/__tests__/__snapshots__/AddSystemModal.tests.js.snap
src/SmartComponents/BaselinesPage/BaselinesPage.js
src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaseline/__tests__/EditBaseline.tests.js
src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaseline/__tests__/__snapshots__/EditBaseline.tests.js.snap
src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaselinePage.js
src/SmartComponents/BaselinesPage/EditBaselinePage/SystemNotification/__tests__/__snapshots__/SystemNotification.tests.js.snap
src/SmartComponents/BaselinesPage/__tests__/BaselinesPage.tests.js
src/SmartComponents/BaselinesPage/__tests__/__snapshots__/BaselinesPage.tests.js.snap
src/SmartComponents/BaselinesTable/BaselinesTable.js
src/SmartComponents/DriftPage/DriftPage.js
src/SmartComponents/DriftPage/DriftTable/DriftTable.js
src/SmartComponents/DriftPage/DriftTable/__tests__/DriftTable.tests.js
src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap
src/SmartComponents/DriftPage/__tests__/__snapshots__/DriftPage.tests.js.snap
src/SmartComponents/EmptyStateDisplay/EmptyStateDisplay.js
src/SmartComponents/SystemsTable/__tests__/__snapshots__/SystemsTable.tests.js.snap

Ticket: [RHIF-122](https://issues.redhat.com/browse/RHIF-122)

chore: Migrate to useChrome

---

src/Routes.js
src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaselinePage.js

A partial cause of https://issues.redhat.com/browse/RHIF-207 is that the document title isnt updated properly. This PR introduces the chrome hook.
Associated Jira ticket: # (RHIF-265)
Navigate to all pages verify that the document changes appropriately

fix(RHIF-265): adopt useChrome updateDocumentTitle

---

src/SmartComponents/SystemsTable/NotificationsSystemsTable.js

This PR implements the group filtering in Drift baselines table page. Currently the backend PR associated with this is only on QA, but as for the testing of the PR, simply navigate to a baseline's details, and then select the groups filter.

feat(ESSNTL-3722): Add groups column to baselines detail page

---

README.md

New line in README to trigger release

---

src/SmartComponents/AddSystemModal/__tests__/__snapshots__/AddSystemModal.tests.js.snap
src/SmartComponents/BaselinesPage/DeleteBaselinesModal/DeleteBaselinesModal.js
src/SmartComponents/BaselinesPage/DeleteBaselinesModal/__tests__/__snapshots__/DeleteBaselinesModal.tests.js.snap
src/SmartComponents/BaselinesPage/EditBaselinePage/DeleteFactModal/DeleteFactModal.js
src/SmartComponents/BaselinesPage/__tests__/__snapshots__/BaselinesPage.tests.js.snap
src/SmartComponents/BaselinesTable/BaselinesToolbar/__test__/__snapshots__/BaselinesToolbar.test.js.snap
src/SmartComponents/BaselinesTable/__tests__/__snapshots__/BaselinesTable.tests.js.snap

https://issues.redhat.com/browse/RHINENG-1043

Add warning icon to delete modals

---

src/SmartComponents/AddSystemModal/__tests__/__snapshots__/AddSystemModal.tests.js.snap
src/SmartComponents/BaselinesPage/__tests__/__snapshots__/BaselinesPage.tests.js.snap
src/SmartComponents/BaselinesTable/BaselinesTable.js

fix(BaselinesTable): RHINENG-2325 - Add padding to footer via TableToolbar

---

src/SmartComponents/SystemsTable/NotificationsSystemsTable.js

Implements https://issues.redhat.com/browse/RHINENG-1844.
Sort by the group column in the baselines associated systems tab (/drift/baselines/%id) and in the add systems modal (both on the comparison view and the baselines associated systems view).
The Inventory change is not yet merged to ensure that the tenant apps support sorting first and avoid breaking change.
1. Pull this Inventory PR locally https://github.com/RedHatInsights/insights-inventory-frontend/pull/2070.
2. Run Drift with this PR `npm run start -- --port=8004`
3. Run Inventory with `LOCAL_APPS=drift:8004~http npm run start:proxy`
4. Navigate to the updated views (in stage-stable environment) and make sure you can sort by system groups.

feat(RHINENG-1844): Make group column sortable

---

README.md

Useless README change to trigger new build

---

config/prod.webpack.config.js

Updates the drift prod webpack config

fix(webpack): Update drift prod webpack configs

---

package-lock.json

https://issues.redhat.com/browse/RHINENG-8447

chore: Bump sanitize-html to fix CVE

---

src/Routes.js

This is a follow up PR for https://issues.redhat.com/browse/RHINENG-5919 

feat(RHINENG-5919): Zero state checks for only RHEL systems

---

src/Routes.js
src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaselinePage.js

Resolves: https://issues.redhat.com/browse/RHINENG-9387
Updates page titles according to 'Current concept' column, single line treatment in this [sheet](https://docs.google.com/spreadsheets/d/1Uhwn6i9B383xUbnRQ2IWY3EZ6dihc-UfkHxnR_c7zXI/edit#gid=1001620868)

chore(RHINENG-9387): update page titles

---

package-lock.json

https://issues.redhat.com/browse/RHINENG-10145

chore(deps): Update micromatch to fix a CVE
