src/SmartComponents/DriftPage/DriftTable/__tests__/AddSystem.test.js, src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/AddSystem.test.js.snap
Let me know if you think this test should be more robust. To be honest, I think we're only testing for proper rendering at this point. Otherwise we could maybe test that clicking the button would call the function, but that seems better tested here: https://github.com/RedHatInsights/drift-frontend/blob/master/src/SmartComponents/DriftPage/DriftTable/DriftTable.js#L101
=> Add test for Add System Button

src/SmartComponents/DriftPage/DriftTable/DriftTable.js
If you switched from filtering by View: All to another filter, when you try to go back to View: All, the table would not populate any information.
This is because this line is changing the state to be equal to "All" instead of the default "all": https://github.com/RedHatInsights/drift-frontend/blob/master/src/SmartComponents/DriftPage/FilterDropDown/FilterDropDown.js#L47
=> Fixes issue with filtering by all

src/SmartComponents/DriftPage/DriftTable/DriftTable.js, src/SmartComponents/DriftPage/Pagination/Pagination.js
The double export caused the TablePagination to be exported without
connecting all of the redux attributes.
=> TablePagination was being exported without redux

src/SmartComponents/modules/reducers.js
Without fix, in Chrome, if you click the fact sort button, the facts would not change sorting.
=> Fix fact sort in Chrome

src/SmartComponents/modules/reducers.js
In Add System, if you click the checkbox next to "Name" and run a compare or click the "X" to close the modal, The table gets trapped in a loading state because the system id submitted to the api is 0, which it can't find.
With this fix, we check that the id added to the array of system ids to run the compare against is not 0 and not null before we add it to the list of ids.
=> Fix System ID = 0

src/SmartComponents/modules/reducers.js
Previously, the state filter only worked on nested facts. Now it works on nested and non-nested facts
=> Fix state filter on non-nested facts

src/SmartComponents/modules/reducers.js
Before, when expanding a row, you would be kicked to page 1, but the page number would remain the same as the previous page you were on.
Now, when expanding a row, you remain on the page you are currently on.
=> Expanding Rows doesn't kick you to page 1

src/SmartComponents/DriftPage/Pagination/Pagination.js
Before, when you changed the number of items shown per page, the table would render and you would remain on the same page you were previously on, even if that page did not exist.
Now, you are automatically returned to page 1 when you updated the number of items per page.
=> Updating items per page returns to page 1

src/App.scss, src/SmartComponents/DriftPage/DriftTable/DriftTable.js
Left border and dropdown carat turn blue when a category is expanded. Reverts back when collapsed.
=> Add blue bar to nested facts when expanded

src/SmartComponents/modules/reducers.js
This works to show the error, but is still broken if you try to close the alert. That will be fixed in another pr.
=> Catch 400 error when too many system Ids are in url

src/SmartComponents/ErrorAlert/ErrorAlert.js
Removed resetSelectedIds from ErrorAlert component as it was removed from the code base in a previous PR: https://github.com/RedHatInsights/drift-frontend/pull/108
=> Closing error alert properly restores previous state

src/SmartComponents/AddSystemModal/AddSystemModal.js
The bug is, when you select a system from the modal on page 1, then go to page 2 and select another system and click compare, you only submit the selected system of the page you are currently on. By changing to selectedSystemIds, we are submitting all systems that have been selected in the modal. Systems are added and taken away from the selectedSystemIds array each time the modal is opened.
=> On running fetch, the submitted ids comes from the selectedSystemIds

src/SmartComponents/DriftPage/DriftTable/DriftTable.js
We changed the table to render a table if there were ids stored in systemIds: https://github.com/RedHatInsights/drift-frontend/pull/112 If you had an empty state, then tried to add a system but got a 500 error, it would revert to an empty table, but because there was an id in systemIds array, it would populated an empty table. The id is only cleared out after the rendering.
I've changed it to check for fullCompareData because in the same instance above, the fullCompareData will be empty. Otherwise, if you had previous fullCompareData before the 500, you would convert back to that without getting the empty table to flash before the compare.
=> On closing 500 error, table populated with no data

src/App.scss, src/SmartComponents/DriftPage/DriftTable/DriftTable.js, src/SmartComponents/modules/__tests__/reducer-test.js, src/SmartComponents/modules/actions.js, src/SmartComponents/modules/reducers.js, src/store/index.js
Fact column should always be sorted by either ascending or descending. It will remain blue.
State column should start turned off. The sorting icon should be gray when turned off and will turn black when hovered over with the mouse. The state column will turn blue in conjunction with the fact column when set to ascending or descending. When the state sort is turned off, it will no longer be blue.
The state sort will take priority in the sorting pattern when turned on.
=> Fix two-column sorting on table

package.json
This should allow drift to rebuild the frontend every night using the latest Patternfly packages.
=> Add a nightly build script

src/SmartComponents/BaselinesPage/CreateBaselineButton/CreateBaselineButton.js
Before, we weren't updating the addSystemModalOpened to false, so it rendered incorrectly.
=> Fixes bug when creating first baseline

src/SmartComponents/DriftPage/DriftPage.js
Before, the toolbar didn't show up if only a baseline was in the comparison chart. Now, we check a `baselines` array to see if it's greater than 0 and if so, we show the toolbar.
=> Fix toolbar on system comparison table

src/SmartComponents/BaselinesTable/redux/__tests__/baselinesTableReducer.fixtures.js, src/SmartComponents/BaselinesTable/redux/helpers.js, src/SmartComponents/DriftPage/DriftTable/DriftTable.js
Add systems table can not be updated from our app, but must be done from Inventory.
The last sync for baselines table (add system modal and baselines page table) and time in system comparison table have been updated
=> Updated time-date stamps to match UX requirements

src/SmartComponents/DriftPage/SearchBar/SearchBar.js
Bug: Add a lot of systems to a comparison (20+) then start typing in the fact filter bar. Each letter will fire off an action and will freeze up the system as it sorts the entire list.
Fix: There should be a 1000 millisecond delay after typing before the action fires off. If you continue typing, the timer will reset.
=> Fixes delay in fact filter when a lot of comparisons are being made

src/SmartComponents/modules/reducers.js
Previously, only systems were used when creating the CSV file header.
Instead, use both systems and baselines if available.
=> use baselines and systems when creating CSV header

src/SmartComponents/BaselinesPage/BaselinesPage.js, src/SmartComponents/BaselinesTable/BaselinesTable.js, src/SmartComponents/BaselinesTable/redux/actions.js, src/api.js
This change moves the empty state logic and fetching logic up to the
page itself and out of the table. This simplifies the table and lets
the page control the flow. Given the Page component is where all of
the parts are composed it necessitates that the logic of what to
present is controlled here.
=> Add search bar to Baselines table

src/SmartComponents/DriftPage/DriftTable/DriftTable.js, src/SmartComponents/modules/reducers.js
Fixes Reset view filter to 'all' when only one system remains in the list
Fixes When removing all systems/baselines by 'Clear all comparisons' option, all filters must be reset to 'selected'
=> Resets filters when 1 or no systems/baselines remain

src/SmartComponents/AddSystemModal/AddSystemModal.js, src/SmartComponents/BaselinesTable/BaselinesTable.js, src/SmartComponents/BaselinesTable/redux/__tests__/baselinesTableActions.tests.js, src/SmartComponents/BaselinesTable/redux/__tests__/baselinesTableReducer.tests.js, src/SmartComponents/BaselinesTable/redux/actions.js, src/SmartComponents/BaselinesTable/redux/baselinesTableReducer.js
This reworks the select logic in order to fix a bug where selecting a baseline in the system modal would not persist. Before this fix if you clicked on the System tab or performed a baseline search, any selected baselines would lose their selections. Now you should be able to switch back and forth or perform search without losing any selection.
This has failing tests and some code cleanup yet to be done. @johnsonm325 wanted you to see the changes I was proposing to the logic as this moves some of it out of the component and into redux.
=> Allow persistent baseline select in modal

src/SmartComponents/BaselinesPage/CreateBaselineModal/CreateBaselineModal.js
The radio buttons did not have a shared name, so users were able to
select more than one at a time. This commit adds a name.
=> link radio buttons together to disable multiselect

src/SmartComponents/BaselinesPage/EditBaseline/EditBaseline.js, src/SmartComponents/BaselinesPage/EditBaseline/FactKebab/FactKebab.js, src/SmartComponents/BaselinesPage/EditBaseline/FactModal/FactModal.js, src/SmartComponents/BaselinesPage/EditBaseline/FactModal/redux/reducers.js, src/SmartComponents/BaselinesPage/EditBaseline/helpers.js
This makes the various incarnations of the fact modal target
their use case more. For example, when editing a category the
title will reflect such. The same for sub facts.
This is essentially a no break test of functionality for creating and editing facts and categories. The titles of the modal should reflect the action as well as the options present reflect the kind of item being created or edited.
* Add Fact
* Add Category
* Edit Fact
* Edit Sub Fact
* Edit Category
=> Introduce more focused fact modals based on type of fact

src/SmartComponents/DriftPage/DriftTable/DriftTable.js
If all systems and baselines were removed in a comparison, followed
by a comparison of just baselines the internal saved set of system
ids would not reset.
=> Fix ghost selection comparison when removing a system

.travis/custom_release.sh
Pushes to "qa" branch will now build and push to qa-beta and qa-stable.
This change moves the frontend closer to a model similar to our
backends.
=> Switch to use of "qa" branch

src/App.scss
This fixes a bug where a filter applied to the comparison table causes the height to adjust, thus cutting off the dropdown for historical profiles. I've adjusted the minimum height to 500 to avoid this.
=> Increase min-height of comparison table to avoid dropdown cutoff

src/SmartComponents/DriftPage/DriftTable/DriftTable.js, src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap, src/SmartComponents/HistoricalProfilesDropdown/HistoricalProfilesDropdown.js, src/SmartComponents/SystemsTable/reducers.js
Because the most recent hsp timestamp is an exact match of the current system, I have opted to pop off the most recent hsp timestamp from the hsp fetched data instead of trying to match the hsp timestamp with the system timestamp.
=> Fix hsp-only compare and hsp dropdown in beta only

src/App.scss, src/SmartComponents/AddSystemModal/AddSystemModal.js, src/SmartComponents/AddSystemModal/__tests__/__snapshots__/AddSystemModal.tests.js.snap, src/SmartComponents/DriftPage/DriftTable/DriftTable.js, src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap, src/SmartComponents/DriftPage/__tests__/__snapshots__/DriftPage.tests.js.snap, src/SmartComponents/HistoricalProfilesDropdown/HistoricalProfilesDropdown.js, src/SmartComponents/HistoricalProfilesDropdown/__tests__/HistoricalProfilesDropdown.tests.js, src/SmartComponents/HistoricalProfilesDropdown/__tests__/__snapshots__/HistoricalProfilesDropdown.tests.js.snap, src/SmartComponents/SystemsTable/reducers.js
Fixes:
- Adding/Removing reference removes HSPs added post initial modal selection from URL
- Adding HSPs via table removes reference_id from URL
- HSP close 'x' does not work as expected
- Closing system/baseline where reference_id is set does not remove reference_id from URL
- Baseline marked as reference doesn't persist when adding more systems/baselines
- HSPs selector gets truncated on system selection modal
=> Fix HSP and reference bugs

src/SmartComponents/AddSystemModal/AddSystemModal.js, src/SmartComponents/AddSystemModal/__tests__/__snapshots__/AddSystemModal.tests.js.snap, src/SmartComponents/BaselinesPage/EditBaseline/EditBaselineNameModal/EditBaselineNameModal.js, src/SmartComponents/BaselinesPage/EditBaseline/EditBaselineNameModal/__tests__/__snapshots__/EditBaselineNameModal.tests.js.snap, src/SmartComponents/BaselinesPage/EditBaseline/EditBaselineToolbar/EditBaselineToolbar.js, src/SmartComponents/BaselinesPage/EditBaseline/__tests__/__snapshots__/EditBaseline.tests.js.snap, src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap, src/SmartComponents/DriftPage/__tests__/__snapshots__/DriftPage.tests.js.snap
Fixes:
- Change 'Choose system' title to 'Add to comparison'
- Rename 'Edit title' to 'Edit name' in Baselines edit screen
- On the baseline edit page, change Add fact to 'Add/edit fact or category'
=> Change wording on buttons and modals

src/SmartComponents/DriftPage/DriftTable/DriftTable.js
1. Add two systems to comparison (system_A, system_B)
2. Set system_A as reference
3. Remove system_A by clicking X
ERROR 1: The URL still shows system_A as reference
4. Add system_A again
5. system_A is reference
Expected: When I remove the system that is reference from comparison, URL doesn't show a reference_id, and when I add the system again, it is not set as reference
=> Correctly remove reference when removing reference from comparison

src/SmartComponents/DriftPage/DriftFilterChips/DriftFilterChips.js
When you apply a fact name filter on comparison table, the filter chips should show 'Fact name' instead of simply 'Name'. This fix was previously applied, but there was a regression. This PR fixes that regression.
=> Fix regression with fact name in drift filter chips

src/SmartComponents/SystemsTable/SystemsTable.js
We are working on inventory refactoring, since we'd like to fully use hooks and such we have to use App's react dependency. With this being used react-redux needs to be passed from application as well. If you are cautious about the size of your bundle I can pick only the functions really required by inventory.
=> Pass react redux to inventory loader as well

package-lock.json, package.json, src/SmartComponents/AddSystemModal/__tests__/__snapshots__/AddSystemModal.tests.js.snap, src/SmartComponents/BaselinesPage/EditBaseline/__tests__/__snapshots__/EditBaseline.tests.js.snap, src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap, src/SmartComponents/SystemsTable/SystemsTable.js
New inventory component heavily relies on hooks including hooks from react-redux to make the component more performant. Drift was using older version of react-redux so I've updated it to newest version (there are no breaking changes) and inventory is now working again.
@ehelms I've also included the showTags prop since we are messing in the same file as #331
=> Modernize inventory component by using function component

package-lock.json, package.json, src/SmartComponents/SystemsTable/SystemsTable.js
There is a new feature brewing in chrome, building chrome with webpack [1]. This PR passes newly required dependencies. In future we'll use Federated modules [2] so there won't be a need for these changes, but this is required as a mid-step solution.
[1] https://github.com/RedHatInsights/insights-chrome/pull/842
[2] https://webpack.js.org/concepts/module-federation/
=> Pass pf react core to inventory to properly render inventory

src/SmartComponents/modules/__tests__/reducer-test.js, src/SmartComponents/modules/reducers.js
1. Add several systems to the comparisons
2. Expand some/all subfacts
3. Click on "Clear all comparisons" button
4. Add new systems
5. Any subfacts previously expanded, remain expanded
On fix, step 5 all subfact will be collapsed
=> Remove expanded rows in redux on clear comparison

src/SmartComponents/BaselinesPage/CreateBaselineModal/CreateBaselineModal.js, src/SmartComponents/SystemsTable/SystemsTable.js, src/store/reducers.js
1. Baselines -> Create baseline -> Copy an existing system
2. Find a system with hsps and select an hsp, but don't create the baseline
3. Select Copy an existing baseline
4. Select Copy an existing system. The name column is blank for all systems.
=> Fixes Empty system names in create baseline modal

src/SmartComponents/BaselinesPage/EditBaseline/redux/reducers.js
To reproduce:
1. View a baseline with no facts (empty baseline)
2. Attempt to edit the baseline name, but simply cancel the edit
3. You shouldn't see the empty state for the baseline, but instead an empty table
=> Fix no empty state when viewing baseline

src/App.js, src/SmartComponents/AddSystemModal/AddSystemModal.js, src/SmartComponents/AddSystemModal/__tests__/AddSystemModal.tests.js, src/SmartComponents/AddSystemModal/__tests__/__snapshots__/AddSystemModal.tests.js.snap, src/SmartComponents/BaselinesPage/BaselinesPage.js, src/SmartComponents/DriftPage/DriftPage.js, src/SmartComponents/DriftPage/DriftTable/DriftTable.js, src/SmartComponents/DriftPage/DriftTable/__tests__/DriftTable.tests.js, src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap, src/SmartComponents/DriftPage/__tests__/__snapshots__/DriftPage.tests.js.snap, src/SmartComponents/SystemsTable/SystemsTable.js
To test, go to src/App.js and change the values of permissions to false as needed. Specifically, change this line:
https://github.com/johnsonm325/drift-frontend/blob/527a28a0bd882347dab6a9b621945628bf25828a/src/App.js#L73
to:
`inventoryRead: /*hasInventoryReadPermissions*/false`
And, change this line:
https://github.com/johnsonm325/drift-frontend/blob/527a28a0bd882347dab6a9b621945628bf25828a/src/App.js#L19
to:
`//hasInventoryReadPermissions,`
Now, if you try to view the inventory/systems table via the add systems modal or the create baseline modal, you should see the lock icon telling you you don't have permissions.
=> Show disabled state with no inventory permissions

src/SmartComponents/BaselinesPage/CreateBaselineModal/CreateBaselineModal.js
- Navigate to Baselines
- Click Create baseline
- Select Copy an existing baseline
- Enter baseline name
- Select Copy an existing system
- The modal disappears, an empty page is displayed..
=> Fix copy existing system modal from disappearing

src/SmartComponents/BaselinesPage/BaselinesPage.js, src/SmartComponents/BaselinesPage/CreateBaselineButton/CreateBaselineButton.js, src/SmartComponents/BaselinesPage/CreateBaselineButton/__tests__/CreateBaselineButton.tests.js, src/SmartComponents/BaselinesPage/CreateBaselineButton/__tests__/__snapshots__/CreateBaselineButton.tests.js.snap, src/SmartComponents/BaselinesPage/__tests__/__snapshots__/BaselinesPage.tests.js.snap, src/SmartComponents/BaselinesTable/BaselinesToolbar/__test__/__snapshots__/BaselinesToolbar.test.js.snap, src/SmartComponents/BaselinesTable/__tests__/__snapshots__/BaselinesTable.tests.js.snap
When there is an empty baselines list and the user has baselines write permissions, the create baselines button is disabled when it should not be.
=> Fix disabled create baseline button if there are no existing baselines

src/SmartComponents/AddSystemModal/AddSystemModal.js, src/SmartComponents/AddSystemModal/__tests__/__snapshots__/AddSystemModal.tests.js.snap, src/SmartComponents/BaselinesPage/CreateBaselineModal/CreateBaselineModal.js, src/SmartComponents/SystemsTable/SystemsTable.js, src/SmartComponents/SystemsTable/__tests__/SystemsTable.tests.js, src/SmartComponents/SystemsTable/__tests__/__snapshots__/SystemsTable.tests.js.snap, src/SmartComponents/SystemsTable/__tests__/fixtures.js, src/store/__tests__/reducer-test.js, src/store/reducers.js
Bulk selector in systems table on add systems modal should work to be able to select an entire page of systems. If you select an entire page and then go to the next page, those selections will still be selected. It keeps a running total. Because the api requests paginated data, you cannot select the entire inventory system at once.
Definitely mess around with this and try to break it. Try adding filters, sorting and selecting/deselecting things to make sure I'm not missing a key part here.
The bulk selector in the systems table on the create baseline modal should be disabled as you can only select a single system to copy from.
=> Fix bulk select in Systems Table

src/SmartComponents/BaselinesPage/EditBaseline/EditBaseline.js, src/SmartComponents/BaselinesPage/EditBaseline/__tests__/EditBaseline.tests.js
To reproduce:
1. Make sure you don't have baseline read permissions and try to view a baseline
2. Breadcrumb and title should show the name of the baseline
This fix will ensure that the breadcrumb only shows a link back to baselines list and the title will say 'Baseline'.
=> Baseline name doesn't show with no read permissions

src/SmartComponents/DriftPage/DriftTable/DriftTable.js, src/SmartComponents/DriftPage/DriftTable/__tests__/DriftTable.tests.js
- Add two systems to comparison
- Add hsps of one system to comparison
- Make an hsp the reference
- Remove the original system
- Verify all hsps have been removed
The hsp is removed but its reference id stays in the URL and that prompts a blocking error message.
This fix removes the system along with its hsps and no reference is set in URL.
This fix also updates some incorrect behaviors with automatic reference being set on a baseline. The general rule is:
If there is NOTHING being compared, and a baseline & system is added, the baseline should be set as reference.
If there is something there already, don’t auto-set.
Previously, if a system was added to a comparison, and then a baseline was added, we automatically referenced the baseline. But in this case, something was 'there already', …
=> Removes HSP as reference when parent system removed from comparison

src/SmartComponents/BaselinesPage/EditBaseline/EditBaseline.js, src/SmartComponents/BaselinesPage/EditBaseline/__tests__/EditBaseline.tests.js, src/SmartComponents/BaselinesPage/EditBaseline/__tests__/__snapshots__/EditBaseline.tests.js.snap
To reproduce:
- Go to Baselines page with an empty state (no baselines)
- Create a baseline
- From the edit baseline page, click the breadbrumb to go back to the baselines list
The baselines list will still show empty. If you refresh, you'll see the baseline you just created.
This fix will show the new baseline you created after you click the breadcrumb.
=> Baselines list loads on breadcrumb click

src/SmartComponents/HistoricalProfilesDropdown/HistoricalProfilesDropdown.js, src/SmartComponents/SystemsTable/SystemsTable.js
- Open Add to comparison modal
- Select several HSPs
- Click Select all
- Click Deselect all
The HSP selector shows no. of selected HSPs even though none are selected.
This fix updates the badge count when using the bulk select 'Select none' to 0.
=> Update HSP badge count on Bulk Select 'Select none'

src/SmartComponents/DriftPage/DriftTable/DriftTable.js
Two issues were fixed here.
First:
- Add two systems to comparison
- Make one a reference
- Remove the system that is the reference
Get an error.
Second:
- Select two systems for comparison
- Make one of them the reference
- Remove the other, then remove the reference host
An error: "must specify at least one of system, baseline, or HSP" is displayed. See screenshot.
=> Fix issue with removing system as reference

src/SmartComponents/BaselinesPage/CreateBaselineModal/CreateBaselineModal.js
If you click 'copy from an existing system' on the create baseline modal, you'll see the loading icon beside the text 'copy from an existing system'. This PR moves that icon below the text.
=> Relocate loading icon on create baseline modal

src/SmartComponents/DriftPage/DriftFilterChips/DriftFilterChips.js, src/SmartComponents/modules/reducers.js
We decided not to go with the new names at this time, so removing them from beta.
=> Remove alternative filter names from beta

src/SmartComponents/BaselinesTable/BaselinesTable.js, src/SmartComponents/DriftPage/DriftTable/ComparisonHeader/ComparisonHeader.js, src/SmartComponents/DriftPage/DriftTable/DriftTable.js, src/SmartComponents/DriftPage/DriftTable/ReferenceSelector/ReferenceSelector.js, src/SmartComponents/DriftPage/DriftTable/ReferenceSelector/__tests__/ReferenceSelector.tests.js, src/SmartComponents/DriftPage/DriftTable/ReferenceSelector/__tests__/__snapshots__/ReferenceSelector.tests.js.snap, src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap, src/SmartComponents/StateIcon/StateIcon.js, src/SmartComponents/modules/__tests__/reducer-test.js, src/SmartComponents/modules/__tests__/reducer.fact-filter-fixtures.js, src/SmartComponents/modules/__tests__/reducer.fixtures.js, src/SmartComponents/modules/__tests__/reducer.state-filter-fixtures.js, src/SmartComponents/modules/__tests__/state-filter.fixtures.js, src/SmartComponents/modules/helpers.js, src/SmartComponents/modules/reducers.js
Tooltips should be on the following:
- State icons
- Tooltips should read differently for same, different and incomplete data
- Different tooltips should be different if a reference is set (Same and incomplete remain unchanged)
- Tooltips should reference category vs. row if it is a category
- Icons next to baseline/system/hsp name
- Reference selector
- Tooltip should read differently on set reference vs. unset reference
=> Add tooltips to icons in comparison table

src/SmartComponents/BaselinesPage/EditBaseline/EditBaselineToolbar/EditBaselineToolbar.js
- Create a baseline from scratch
- Add a category to the baseline
The add fact or category button is inactive
=> Enable Add Fact Button when baseline only has an empty category

src/SmartComponents/AddSystemModal/__tests__/__snapshots__/AddSystemModal.tests.js.snap, src/SmartComponents/BaselinesPage/__tests__/__snapshots__/BaselinesPage.tests.js.snap, src/SmartComponents/BaselinesTable/BaselinesToolbar/BaselinesToolbar.js, src/SmartComponents/BaselinesTable/BaselinesToolbar/__test__/__snapshots__/BaselinesToolbar.test.js.snap, src/SmartComponents/BaselinesTable/__tests__/__snapshots__/BaselinesTable.tests.js.snap
If you filter the baselines by name, the chip group that appears in the toolbar will read "Fact name". With this fix, it should read "Baseline name".
=> Change 'Fact name' to 'Baseline name' on baseline table chip

src/SmartComponents/modules/__tests__/helpers-tests.js, src/SmartComponents/modules/helpers.js
To reproduce:
1. Add a system to a comparison that contains a category with state SAME and at least 1 INCOMPLETE_DATA. The state on the category will be DIFFERENT in this case.
2. Click 'Clear all filters' link next to the chips.
This should cause an error. You may not see it, but the Incomplete data chip should remain in the chips, which is not what we expect. We expect to see all chips cleared out.
This PR fixes the error and properly removes all chips.
=> Fix break on 'Clear all filters' drift table

src/SmartComponents/DriftPage/DriftTable/DriftTable.js, src/SmartComponents/StateIcon/StateIcon.js
1. Create a comparison
2. See that tooltips appear
3. Sort by state and see that some tooltips don't appear
This PR fixes this issue and all tooltips appear on state sort.
=> Fix broken tooltips on state sort

src/SmartComponents/AddSystemModal/AddSystemModal.js, src/SmartComponents/AddSystemModal/__tests__/AddSystemModal.tests.js, src/SmartComponents/AddSystemModal/__tests__/__snapshots__/AddSystemModal.tests.js.snap, src/SmartComponents/BaselinesPage/CreateBaselineModal/CreateBaselineModal.js, src/SmartComponents/BaselinesPage/CreateBaselineModal/__tests__/CreateBaselineModal.tests.js, src/SmartComponents/GlobalFilterAlert/GlobalFilterAlert.js, src/SmartComponents/GlobalFilterAlert/__tests__/GlobalFilterAlert.tests.js, src/SmartComponents/GlobalFilterAlert/__tests__/__snapshots__/GlobalFilterAlert.tests.js.snap
This PR adds an alert to the top of the add system and create baseline modals that shows any active global filters. The filter will only show up if you choose a filter. If you only select 'All Workloads' but don't select any tags or SAP IDs, then you won't see the alert.
You should be able to close this alert by clicking the 'X'. If you back out of the modal and go back in, the alert should reappear.
=> Add active global filters

src/SmartComponents/BaselinesPage/BaselinesPage.js, src/SmartComponents/BaselinesPage/EditBaseline/EditBaseline.js, src/SmartComponents/DriftPage/DriftTable/DriftTable.js, src/SmartComponents/EmptyStateDisplay/EmptyStateDisplay.js
To test:
1. Go to comparison landing page
2. Open developer tools with F12 (or function + F12)
3. Click the `Elements` tab at the top of the dev tools window
4. Press `Ctrl` + `F` to find a string in the html
The following should be found as the `data-ouia-page-type` when you search on the corresponding pages:
- Comparison landing page (no comparison) - `comparison-list`
- Comparison (at least one system/baseline/hsp compared) - `comparison-view`
- It should change back to `comparison-list` if you clear all comparisons.
- Baselines page - `baseline-list`
- Edit baseline - `baseline-view`
- Here, you should also find the id of the baseline you selected by searching for `data-ouia-page-object-id`
=> Add additional app data to DOM to improve Pendo

src/SmartComponents/modules/__tests__/reducer-test.js, src/SmartComponents/modules/reducers.js
To reproduce:
1. Add a system for comparison
2. Filter by fact.  Works correctly.
3. Add another system.
The facts are no longer filtered, although the filter chip is still there.
This PR fixes the bug where an empty array was being added to the a filter function in the reducer on FETCH_COMPARE_FULFILLED instead of passing the activeFactFilter in the state.
=> DRFT-113 Fix persistent activeFactFilter on new fetch

src/SmartComponents/modules/helpers.js
To reproduce:
1. Create a comparison
2. Add a filter for category (include full category name to filter out all but the full category. installed_packages is a good example) and press Enter
3. Begin typing in a new filter for a regular fact that is alphabetically after your category (if your category is installed_packages, type in something like os_release)
The comparison will not show the os_release in the filtered facts. I replaced a `break` with a `continue` because I was matching the category and then breaking out of the entire loop, ignoring every fact and category that came after it. Choosing to `continue` just jumps to the next iteration rather than breaking out of the entire loop.
=> DRFT-112 Fix multi-filter broken with category filter

src/SmartComponents/modules/__tests__/reducer-test.js, src/SmartComponents/modules/reducers.js
To repro:
Add two systems
Apply filter by name, press enter
Apply another name filter, don't press enter
Clear all comparisons
Add a system
Only one of the name filters remains applied. This PR keeps all filters on clear all comparisons.
=> DRFT-121 Fix clear all comparisons for activeFactFilters

package-lock.json, package.json
The CSS scope was not properly assigned to minified CSS. Therefore the default PF styling was overriding the scoped CSS thus causing visual bugs.
You can reproduce this locally when running the app locally via `npm run prod`
we should no longer need: https://github.com/RedHatInsights/drift-frontend/pull/426
@johnsonm325
=> Fix missing styles in prod build.

config/prod.webpack.config.js, package-lock.json, package.json
Since drift is using custom release that releases stable builds from master branch we have to pass in `deployment` config variable to shared config. This has been enabled in most recent version.
=> Fix stable build by using new version of config and passing custom deployment

package-lock.json, package.json
The appname used for CSS scoping was accidentally removed in shared
config @beta22.
https://github.com/RedHatInsights/frontend-components/commit/9f7096bba002813ddd4de613a043e1eb52d50983#diff-0ff265c46140a3ca34889b853d585da568e7feee3420f9396a833bbd2584b556L54
cc @johnsonm325
=> Update webpack config

src/SmartComponents/GlobalFilterAlert/GlobalFilterAlert.js, src/SmartComponents/GlobalFilterAlert/__tests__/GlobalFilterAlert.tests.js, src/SmartComponents/GlobalFilterAlert/__tests__/__snapshots__/GlobalFilterAlert.tests.js.snap
Because workloads has been changed and now it is checkbox we have to check if SAP is really selected and if so show the global filter, otherwise no need to show it at all.
=> Check if SAP is selected

src/SmartComponents/GlobalFilterAlert/GlobalFilterAlert.js
To reproduce:
- Spin up fresh drift page with no pre-selected global filters
- Choose a SAP ID (SID) from the global filters, but do not choose a workload
- Click the `Add to comparison` button to view the modal
You should see `Workloads: undefined`
With this fix, the workloads won't show up if you haven't filtered by a workload
=> [DRFT-159] Fix workloads: undefined in global filter alert

src/constants.js
We were importing as `{ version }` when the import of the file is an object. We simply had to import `version` from the returned object.
To reproduce:
1. run `npm run start` on master and see the compiler warning.
This fix will cause the compiler to compile successfully every time instead of with warnings.
=> [DRFT-165] Fix version import in constants.js

src/SmartComponents/modules/__tests__/helpers-tests.js, src/SmartComponents/modules/helpers.js
1. Create comparison with a system having an obfuscated value
2. Hover over state icon to read tooltip
Tooltip should read 'Same - At least one system fact value in this row is redacted.'
This PR correctly sets the tooltip to 'Incomplete data - At least one system fact value in this row is redacted.'
=> [DRFT-135] Fix incorrect tooltip on obfuscated values

src/SmartComponents/AddSystemModal/AddSystemModal.js, src/SmartComponents/DriftPage/DriftPage.js, src/SmartComponents/DriftPage/DriftTable/ComparisonHeader/ComparisonHeader.js, src/SmartComponents/DriftPage/DriftTable/ComparisonHeader/__tests__/ComparisonHeader.tests.js, src/SmartComponents/DriftPage/DriftTable/DriftTable.js, src/SmartComponents/DriftPage/DriftTable/__tests__/DriftTable.tests.js, src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap, src/SmartComponents/DriftPage/DriftToolbar/DriftToolbar.js, src/SmartComponents/DriftPage/DriftToolbar/__tests__/DriftToolbar.tests.js, src/SmartComponents/DriftPage/DriftToolbar/__tests__/__snapshots__/DriftToolbar.tests.js.snap, src/SmartComponents/DriftPage/FilterDropDown/FilterDropDown.js, src/SmartComponents/DriftPage/SearchBar/SearchBar.js, src/SmartComponents/DriftPage/SearchBar/__tests__/SearchBar.tests.js, src/SmartComponents/DriftPage/__tests__/DriftPage.tests.js, src/SmartComponents/DriftPage/__tests__/__snapshots__/DriftPage.tests.js.snap, src/SmartComponents/DriftPage/__tests__/fixtures/DriftPage.fixtures.js, src/SmartComponents/modules/__tests__/reducer.fixtures.js, src/Utilities/SetHistory.js
To test:
- Create a comparison with any number of systems (to test best, add a system, baseline and hsp)
- See the filters and sort in the url
- Modify the url manually to achieve results
- Modify the filters and sorting via normal means (clicking buttons, typing in filters, etc)
- Add and remove systems to ensure that the url properly updates in response to your actions
- Ensure that the page updates in response to your edits to the url
For filtering and sorting, we are using the following rules based on the provided links.
- For filtering rules, see: https://jsonapi.org/recommendations/#filtering
- For sorting rules, see: https://jsonapi.org/format/#fetching-sorting
Here are some rules for how the urls are expected to look:
- Fact name filters are comma separated and follow …
=> [DRFT-144] Add filters and sorting to url

src/SmartComponents/BaselinesPage/CreateBaselineModal/CreateBaselineModal.js, src/SmartComponents/BaselinesPage/CreateBaselineModal/__tests__/__snapshots__/CreateBaselineModal.tests.js.snap, src/SmartComponents/BaselinesPage/__tests__/__snapshots__/BaselinesPage.tests.js.snap
This change will allow us to determine which radio button was selected when a user creates a baseline from the create baseline modal. We will set 3 features in Pendo to track each ouiaId and see how users are creating baselines.
To test, go to the create baselines modal and open the developer tools in your browser. Use the element inspector to select the 'Create Baseline' button (you'll need to type something in the Baseline name input box to get the 'Create baseline' button to be selectable. As you change the selected radio button, you should see the `data-ouia-component-id` update with one of the following strings:
- `copy-baseline-button-fromscratch`
- `copy-baseline-button-copybaseline`
- `copy-baseline-button-copysystem`
=> Change ouiaId for create baseline modal submit button for Pendo

src/SmartComponents/DriftPage/DriftToolbar/DriftToolbar.js, src/SmartComponents/DriftPage/DriftToolbar/__tests__/DriftToolbar.tests.js, src/SmartComponents/DriftPage/DriftToolbar/__tests__/__snapshots__/DriftToolbar.tests.js.snap, src/SmartComponents/DriftPage/__tests__/__snapshots__/DriftPage.tests.js.snap, src/Utilities/SetHistory.js
Two issues here:
1. Duplicate fact filter in url
- Select a system for comparison
- Add a fact name filter like kernel
- Add the fact name again.  The URL becomes: https://ci.cloud.redhat.com/insights/drift/?system_ids=306603e5-288a-401f-8d10-62af6c66889a&filter[name]=kernel,kernel&filter[state]=same,different,incomplete_data&sort=-state,fact
2. Fact filter remains in url after Clear all filters clicked
- Create comparison
- Add a filter (push enter to add or just type it in)
- Click "Clear all filters" link next to chips
- The name filters will remain in the url.
=> Fixes issues with fact filter in url

src/SmartComponents/BaselinesPage/EditBaseline/EditBaseline.js, src/api.js
To reproduce:
- Navigate to baseline details view
- edit fact
- change Fact name
- click Save
Empty, grey view is shown. The fact/category in question is successfully edited/deleted, just the UI breaks.
This PR fixes that issue. The edit baseline table should properly load after modal closes.
=> [DRFT-192] Fixes issue with error when changing baseline fact name

src/Routes.js
Chrome 2 deletes the `document.getElementById('root')` element if a chrome 2 ready app is rendered. Legacy code can cause runtime crashes.
The code can be safely removed because the root class was not used.
cc @johnsonm325
=> Remove React root element mutation.

src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaselinePage.js, src/SmartComponents/SystemsTable/NotificationsSystemsTable.js, src/SmartComponents/SystemsTable/SystemsTable.js
Fixes:
- DRFT-312
- To repro:
- open a baseline
- change to `system notifications` tab
- add several systems, such that there are at least two pages in the table
- change to next page
- The table is stuck on loading, see attached error in console.
- DRFT-317
- To repro:
- Navigate to systems table (for example in Add to Comparison modal)
- All the systems have "1" displayed as the tags count. This amount is displayed for ALL systems, regardless of their actual tags (as can be seen when opening the tags modal).
=> Fix pagination and tags issues with Inventory table

src/SmartComponents/BaselinesPage/EditBaselinePage/SystemNotification/SystemNotification.js
Add `await` to add notifications action to ensure notifications are added before the fetch is fired off.
To repro:
- open a baseline notifications tab
- make sure there is at least one system present
- click Add system
- try to add using Bulk select
- click Submit
New systems added may not be present. Doesn't happen 100% of the time, but happens often enough to find the issue.
=> [DRFT-328] Await add notifications

src/SmartComponents/SystemsTable/NotificationsSystemsTable.js
Go to baseline details
Click "Systems" tab
Click dropdown in toolbar
Hovering over dropdown item doesn't show pointer. This PR fixes that.
=> Add pointer on hover of notifications toolbar dropdown

src/SmartComponents/SystemsTable/SystemsTable.js
- open a baseline
- navigate to system notifications tab
- make sure the table is not empty
- open Add system modal
- click the checkbox on the Bulk selector (selects all)
- click the '50 selected' text on the bulk selector
This PR temporarily removes bulk select component from the Add System modal in baselines notifications.
=> [DRFT-315] Disable bulk select in notifications 'Add System' modal

src/SmartComponents/SystemsTable/NotificationsSystemsTable.js
I have 3 baseline systems.  In the dropdown, it says Select page (0).  I believe it should say 3 in parentheses.
=> Fix number to select in bulk select dropdown

src/SmartComponents/BaselinesPage/EditBaselinePage/SystemNotification/DeleteNotificationModal/DeleteNotificationModal.js, src/SmartComponents/BaselinesPage/EditBaselinePage/SystemNotification/SystemKebab/SystemKebab.js, src/store/reducers.js
- [DRFT-319] The delete baseline notification confirmation prompt says:
- "You have selected to be deleted"
- [DRFT-318] Changed to `You have selected a baseline notification/multiple baseline notifications to be deleted.`
- Fixed typo in title `Delete baseline notificatoin`.
- Changed title to read `Delete baseline notification(s)` depending on number of systems selected.
- Changed confirmation button to read `Delete`.
=> Fix text in delete notification modal

src/SmartComponents/SystemsTable/NotificationsSystemsTable.js
To reproduce:
- open a baseline
- navigate to system notifications
- make sure no systems are selected
- click toolbar kebab
- select Delete notification
The modal appears, and clicking delete does nothing. This PR disables the Delete notification button when no systems are selected.
=> [DRFT-314] Disable delete notification when nothing selected

config/dev.webpack.config.js, src/DevEntry.js, src/bootstrap-dev.js
Dev environment stopped logging redux actions in the browser console. This PR creates a dev-specific entry point into the app where logging is passed, exclusively.
To repro:
Open app and open developer tools in browser
You should not see any redux actions in the console
This fix will expose the action logging.
=> Add DevEntry for redux logging

package-lock.json, package.json
ua-parser-js >= 0.7.14, fixed in 0.7.24, uses a regular expression which is vulnerable to denial of service. If an attacker sends a malicious User-Agent header, ua-parser-js will get stuck processing it for an extended period of time.
=> [DRFT-269] Update ua-parser-js package to 0.7.28

src/App.js, src/SmartComponents/AddSystemModal/AddSystemModal.js, src/SmartComponents/AddSystemModal/__tests__/AddSystemModal.tests.js, src/SmartComponents/AddSystemModal/__tests__/__snapshots__/AddSystemModal.tests.js.snap, src/SmartComponents/BaselinesPage/BaselinesPage.js, src/SmartComponents/BaselinesPage/CreateBaselineModal/CreateBaselineModal.js, src/SmartComponents/BaselinesPage/CreateBaselineModal/__tests__/CreateBaselineModal.tests.js, src/SmartComponents/BaselinesPage/CreateBaselineModal/__tests__/__snapshots__/CreateBaselineModal.tests.js.snap, src/SmartComponents/DriftPage/DriftPage.js, src/SmartComponents/DriftPage/DriftTable/ComparisonHeader/ComparisonHeader.js, src/SmartComponents/DriftPage/DriftTable/ComparisonHeader/__tests__/ComparisonHeader.fixtures.js, src/SmartComponents/DriftPage/DriftTable/ComparisonHeader/__tests__/ComparisonHeader.tests.js, src/SmartComponents/DriftPage/DriftTable/ComparisonHeader/__tests__/__snapshots__/ComparisonHeader.tests.js.snap, src/SmartComponents/DriftPage/DriftTable/DriftTable.js, src/SmartComponents/DriftPage/DriftTable/__tests__/DriftTable.tests.js, src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap, src/store/__tests__/reducer-test.js, src/store/__tests__/reducer.fixtures.js
This PR blocks the HSP icon on:
Add system modal
Comparison table
Create baseline modal
To test:
- Go to this file: https://github.com/johnsonm325/drift-frontend/blob/9cadc3152ab41c4f7c3281606409af07b1a3ce76/src/App.js#L31-L40 and change to this:
```
const handlePermissionsUpdate = (hasCompareRead, hasBaselinesRead, hasBaselinesWrite/*, hasHSPRead*/, hasInventoryRead) => {
setPermissions({
hasCompareReadPermissions: hasCompareRead,
hasBaselinesReadPermissions: hasBaselinesRead,
hasBaselinesWritePermissions: hasBaselinesWrite,
hasHSPReadPermissions: /*hasHSPRead*/false,
hasInventoryReadPermissions: hasInventoryRead,
arePermissionsLoaded: true
});
};
```
- For each of the following, there should be no historical profiles column:
- Go to inventory/systems table on add system modal
- Drift -> …
=> [DRFT-275] Handle no hsp read permissions

src/SmartComponents/AddSystemModal/AddSystemModal.js, src/SmartComponents/AddSystemModal/__tests__/AddSystemModal.tests.js, src/SmartComponents/AddSystemModal/__tests__/__snapshots__/AddSystemModal.tests.js.snap, src/SmartComponents/AddSystemModal/redux/__tests__/addSystemModalReducer.fixtures.js, src/SmartComponents/AddSystemModal/redux/helpers.js, src/SmartComponents/SystemsTable/SystemsTable.js, src/SmartComponents/SystemsTable/__tests__/__snapshots__/SystemsTable.tests.js.snap, src/SmartComponents/helpers.js, src/store/__tests__/reducer-test.js, src/store/reducers.js
To test:
- Navigate to Add to comparison modal
- Click Bulk Selector to select all
- click the Bulk Selector again
The full set of systems on page is added every time we click, making the basket contain duplicates. If we then remove a system from basket, also it's duplicate is removed.
This PR makes sure that when a system, baseline or historical profile is selected, but not compared, and you back out of the add system modal screen, those items are removed from the basket and all selections in the table, when you return to the add system modal, are removed.
This PR also ensures that the bulk selector properly adds and removes systems to the selected basket in the top right corner of the add system modal.
=> [DRFT-262] Fix bulk select in add system modal

src/SmartComponents/AddSystemModal/AddSystemModal.js, src/SmartComponents/AddSystemModal/__tests__/AddSystemModal.tests.js, src/SmartComponents/AddSystemModal/redux/__tests__/addSystemModalReducer.fixtures.js
There are 2 issues.
First, baseline selections are being properly saved. To repro:
add two baselines to comparison
open the add system modal
You should see that the 2 baselines are in the systems basket, but aren't selected in the table.
Second, reference gets removed from comparison with the following actions:
add two baselines to comparison
then add another system or baseline to comparison
Because the baseline selections are empty after second entry into add system modal, the reference id is not present in the comparison.
=> [DRFT-469] Fix errors with basket items not being added or removed

src/SmartComponents/AddSystemModal/__tests__/__snapshots__/AddSystemModal.tests.js.snap, src/SmartComponents/BaselinesPage/EditBaselinePage/SystemNotification/__tests__/__snapshots__/SystemNotification.tests.js.snap, src/SmartComponents/BaselinesPage/__tests__/__snapshots__/BaselinesPage.tests.js.snap, src/SmartComponents/BaselinesTable/__tests__/__snapshots__/BaselinesTable.tests.js.snap, src/SmartComponents/EmptyStateDisplay/EmptyStateDisplay.js, src/SmartComponents/SystemsTable/__tests__/__snapshots__/SystemsTable.tests.js.snap
To repro:
Go to baselines page
Filter so nothing matches
You'll see that the line doesn't break at the sentence change. With this change, the line will break after the first period.
=> [DRFT-246] Make baselines filter empty state 2 lines

src/SmartComponents/DriftPage/DriftToolbar/DriftToolbar.js, src/SmartComponents/DriftPage/DriftToolbar/__tests__/__snapshots__/DriftToolbar.tests.js.snap
To repro:
Create comparison
Apply filter by name
Click reset filter
The filter remains in the url when it should be removed. Also happens if you remove a state filter and then click reset filters.
This PR properly updates the url on reset filter click.
=> [DRFT-740] Update url with reset filters

src/SmartComponents/modules/__tests__/helpers-tests.js, src/SmartComponents/modules/__tests__/reducer.fact-filter-fixtures.js, src/SmartComponents/modules/__tests__/reducer.fixtures.js, src/SmartComponents/modules/helpers.js, src/SmartComponents/modules/reducers.js
To repro:
- Create a comparison
- Use the fact name filter to filter on a fact name, but use uppercase letters instead of lowercase letters.
This should cause the fact you were trying to filter to not show up when you think it should. Now, filters are case-insensitive, so no matter if you use upper or lowercase in the filter or in the fact name, the fact name will show up.
=> [DRFT-608] Make filters case-insensitive

src/SmartComponents/helpers.js
To reproduce:
Go to baselines list
Click "Create baseline"
Select "Copy an existing system or historical profile"
Select an hsp from a system that has an hsp
The blue 'X' icon should appear next to the time stamp for the hsp underneath the name of the system to which it belongs. This PR changes that icon to gray when the cursor is not hovering over it and black when it is.
=> [DRFT-590] 'X' icon in hsp selection should be gray

src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap, src/SmartComponents/StateIcon/StateIcon.js
To reproduce:
Create a comparison that includes a state of incomplete data
The incomplete data icon should be black. This PR updates the color so it's #6A6E73
=> [DRFT-596] Update incomplete data icon to #6A6E73

src/App.scss, src/SmartComponents/DriftPage/DriftTable/DriftTable.js, src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap, src/SmartComponents/DriftPage/__tests__/__snapshots__/DriftPage.tests.js.snap
The only horizontal scrollbar on the comparison table is located at the bottom of the table, therefore scrolling is not optimal when a user has to scroll all the way to the bottom to scroll horizontally. This PR adds a scrollbar to the top so a user can scroll horizontally from the top or the bottom of the page.
This PR does not fully fix the issue as the end goal is to make the top scrollbar sticky at the top of the page so you can scroll horizontally even if you are in the middle of the page where neither scrollbar is visible. Because we are also attempting to make the header row of the table sticky, we are going to implement the stickiness with that PR.
=> [DRFT-539] Add scrollbar to top of comparison table

src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaseline/EditBaseline.js, src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaseline/__tests__/helpers.fixtures.js, src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaseline/__tests__/helpers.tests.js, src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaseline/helpers.js
Because of a discussion in which we decided that a fact and a category can share the same name, we are updating the system-baseline-backend repo with a PR that allows this to happen. This caused some add, deleting and editing of facts, categories and sub facts to work improperly.
This PR allows things to work as usual with a new feature that allows a category and fact to share a name. Facts still can't share names with other facts and categories can't share names with other categories.
=> [DRFT-582] Allow facts and categories to share names

src/App.scss, src/SmartComponents/AddSystemModal/AddSystemModal.js, src/SmartComponents/AddSystemModal/__tests__/__snapshots__/AddSystemModal.tests.js.snap, src/SmartComponents/BaselinesPage/BaselinesPage.js, src/SmartComponents/BaselinesPage/CreateBaselineModal/CreateBaselineModal.js, src/SmartComponents/BaselinesPage/__tests__/__snapshots__/BaselinesPage.tests.js.snap, src/SmartComponents/BaselinesTable/BaselinesTable.js, src/SmartComponents/BaselinesTable/BaselinesToolbar/BaselinesToolbar.js, src/SmartComponents/BaselinesTable/BaselinesToolbar/__test__/__snapshots__/BaselinesToolbar.test.js.snap, src/SmartComponents/BaselinesTable/__tests__/__snapshots__/BaselinesTable.tests.js.snap
To repro
Click 'Add to comparison' on /drift page
Click 'Baselines' tab
Click 'Create baseline' on /drift/baselines page
Click 'Copy and existing baseline' radio button
In both instances you should see that the toolbar has padding on the left. With this PR, we remove that padding. The padding should remain on the baselines table at /drift/baselines.
=> [DRFT-596] Left align baselines toolbar

src/SmartComponents/BaselinesPage/CreateBaselineModal/CreateBaselineModal.js, src/SmartComponents/BaselinesPage/CreateBaselineModal/__tests__/CreateBaselineModal.tests.js, src/SmartComponents/BaselinesPage/CreateBaselineModal/__tests__/__snapshots__/CreateBaselineModal.tests.js.snap, src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaselineNameModal/EditBaselineNameModal.js, src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaselineNameModal/__tests__/EditBaselineNameModal.tests.js, src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaselineNameModal/__tests__/__snapshots__/EditBaselineNameModal.tests.js.snap, src/SmartComponents/BaselinesPage/EditBaselinePage/FactModal/FactModal.js, src/SmartComponents/BaselinesPage/EditBaselinePage/FactModal/__tests__/FactModal.tests.js, src/SmartComponents/BaselinesPage/EditBaselinePage/FactModal/__tests__/__snapshots__/FactModal.tests.js.snap
According to our mocks, errors in the baseline modals should only have the inline text errors under the text input boxes. The error alerts that show up at the top of the modal should be removed. Test errors in these locations to ensure that they've been fixed:
Create baseline modal
Edit baseline modal
Create/Edit fact modal
=> [DRFT-577] Baseline modal errors fix

src/SmartComponents/AddSystemModal/AddSystemModal.js, src/SmartComponents/AddSystemModal/__tests__/__snapshots__/AddSystemModal.tests.js.snap, src/SmartComponents/BaselinesPage/CreateBaselineModal/CreateBaselineModal.js
Before, you couldn't properly load the baselines table in the add system modal or create baseline modal because the new associated systems count column was not being rendered. This PR fixes that.
=> [DRFT-829] Fix baselines table in add system and create baseline

src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap, src/SmartComponents/HistoricalProfilesPopover/HistoricalProfilesPopover.js, src/SmartComponents/HistoricalProfilesPopover/__tests__/HistoricalProfilesPopover.tests.js, src/SmartComponents/HistoricalProfilesPopover/__tests__/__snapshots__/HistoricalProfilesPopover.tests.js.snap
To reproduce:
Select baseline and system to compare
On the Comparison screen, try to add a HSP to the comparison
This causes an error (reference id) and the baseline to disappear from the comparison
Now, the correct set of selected baseline ids is being passed to the component.
=> [DRFT-840] Add correct baseline ids to HistoricalProfilesPopover

src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaseline/__tests__/helpers.tests.js, src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaseline/helpers.js
Before, in the edit baseline details page, if you selected a single sub fact in a category with 2 or more sub facts, the category would receive a checkmark.
Now, if only some of the sub facts of a category are selected, that category receives a partial select icon in the checkbox (a dash '-').
So:
No sub facts selected - Category checbox is empty
Some sub facts selected - Category checkbox shows dash '-'
All sub facts selected - Category checkbox shows checkmark
=> [DRFT-588] Add partial select to category checkbox

src/App.scss, src/SmartComponents/BaselinesTable/BaselinesTable.js, src/SmartComponents/BaselinesTable/NotificationDetails/NotificationDetails.js, src/SmartComponents/BaselinesTable/__tests__/__snapshots__/BaselinesTable.tests.js.snap, src/SmartComponents/NotificationsSwitch/NotificationsSwitch.js
Before, if a system had 0 associated systems, we disabled the Switch. Now, the Switch is always enabled, allowing a user to flip notifications on and off not matter how many systems are associated.
Before, the color of the badge would be blue if notifications were turned on, and gray if notifications were turned off. This action mimicked the color of the switch. This PR disassociates the state of the Switch and the badge color. Now, if there are greater than 0 associated systems, the badge color will be blue, and if there are 0 associated systems, the badge will be gray.
=> [DRFT-918] Update notification switch states

src/SmartComponents/AddSystemModal/SelectedBasket/SelectedBasket.js, src/SmartComponents/AddSystemModal/SelectedBasket/__tests__/SelectedBasket.tests.js, src/SmartComponents/AddSystemModal/SelectedBasket/__tests__/__snapshots__/SelectedBasket.tests.js.snap, src/SmartComponents/AddSystemModal/__tests__/__snapshots__/AddSystemModal.tests.js.snap
Before, in order to apply changes made to the Selected Basket, a user had to click the close button in the popover. Now, a user must click the "Apply changes" button. If a user makes changes to the Selected Basket and either clicks out of the popover or clicks the "X" to close the popover, the changes will NOT be applied.
=> [DRFT-366] Add button to apply changes to Selected Basket

src/SmartComponents/AddSystemModal/AddSystemModal.js, src/SmartComponents/AddSystemModal/__tests__/__snapshots__/AddSystemModal.tests.js.snap, src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap, src/SmartComponents/DriftPage/__tests__/__snapshots__/DriftPage.tests.js.snap
When in the add system baseline modal, if the selected basket popover is open and you scroll on the add system modal, you will eventually see the popover disappear, but the content will remain scrollable on the screen. This PR updates it so if the popover is open and you scroll the add system modal, the popover will close.
=> [DRFT-908] Close Selected Basket popover on modal scroll

src/SmartComponents/AddSystemModal/AddSystemModal.js, src/SmartComponents/AddSystemModal/SelectedBasket/SelectedBasket.js, src/SmartComponents/AddSystemModal/__tests__/__snapshots__/AddSystemModal.tests.js.snap, src/SmartComponents/AddSystemModal/redux/helpers.js, src/SmartComponents/BaselinesTable/BaselinesToolbar/__test__/__snapshots__/BaselinesToolbar.test.js.snap, src/SmartComponents/BaselinesTable/__tests__/__snapshots__/BaselinesTable.tests.js.snap, src/SmartComponents/BaselinesTable/redux/__tests__/baselinesTableReducer.fixtures.js, src/SmartComponents/DriftPage/DriftTable/DriftTable.js, src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap, src/SmartComponents/DriftPage/__tests__/__snapshots__/DriftPage.tests.js.snap
To repro:
- Select 2 hsps from the Add to comparison modal and submit
- Return to the Add to comparison modal.  The Selected count is 0 even though I have 2 hsps selected.
- From here, things get a bit weird.  If I deselect one of the hsps from the hsp popover, the Selected count becomes 1 (ok so far).  If I deselect the other hsp, the Selected count becomes 2 (incorrect).
=> [DRFT-946] Fix hsp selection for selected basket

src/SmartComponents/DriftPage/DriftTable/DriftTable.js
To repro:
Create a comparison with at least 1 system with obfuscated values and a ensure that the fact that includes obfuscation results in a state of 'DIFFERENT' for the row. The easiest way to do this is create an empty baseline and compare the baseline to a system with obfuscation and a system with a value that isn't obfuscated.
Set the baseline as reference (should happen out of the box)
The obfuscated value (check for fqdn or ipv) should be completely gray with a lock icon, but the value set as 'DIFFERENT' will have a red border on the left and the background of the cell is gray. With this PR, the background of the 'DIFFERENT' cell will be red.
There is some discussion about whether or not we would highlight these values as red because ip addresses and fqdn should not be the same as …
=> [DRFT-912] Fix obfuscated cell shading

src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaseline/__tests__/helpers.fixtures.js, src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaseline/helpers.js, src/SmartComponents/BaselinesTable/redux/__tests__/baselinesTableReducer.fixtures.js, src/SmartComponents/BaselinesTable/redux/helpers.js, src/SmartComponents/helpers.js, src/SmartComponents/modules/__tests__/reducer.fixtures.js, src/SmartComponents/modules/helpers.js
For comparison, baseline list and baseline details CSV export, if you export to CSV, you will notice that a comma is added at the end of each row. This PR removes the final comma.
Be aware, in the case of multivalues, if a fact has an empty value, you may notice a comma after the end of the row. So, in the case of this layout:
This output is expected, and okay:
=> [DRFT-914] Remove extra comma at end of row in CSV

src/SmartComponents/DriftPage/DriftTable/DriftTable.js
Before, if you ran a comparison that included multivalues and expanded the category that included multivalues, all subfacts of that category would have a blue left border to show they belong to the category, but any collapsed multivalues would not have the blue left border.
This PR fixes that by including the blue border for the collapsed multivalue.
=> [DRFT-838] Collapsed multivalue should show blue left border

src/App.scss
Before, the tags icon in the inventory table was not left aligned to the text in the header. This PR ensures that it is left-aligned. I also left-aligned the HSP icon to the header as well.
=> [DRFT-904] Left align tags icon in inv table

src/SmartComponents/BaselinesPage/EditBaselinePage/SystemNotification/SystemNotification.js, src/SmartComponents/BaselinesPage/EditBaselinePage/SystemNotification/__tests__/__snapshots__/SystemNotification.tests.js.snap
Before, some of the modals had different sizes. These have been normalized for consistency across the app. Modal widths should be as follows:
1200 px:
- Add system modal
- Create baseline modal
- System notification
560 px:
- Delete baselines modal
- Delete fact modal
- Edit baseline name modal
- Fact modal
- Delete notification modal
=> [DRFT-907] Standarize the width of modals in drift

src/App.scss, src/SmartComponents/DriftPage/DriftTable/ComparisonHeader/ComparisonHeader.js, src/SmartComponents/DriftPage/DriftTable/ComparisonHeader/__tests__/__snapshots__/ComparisonHeader.tests.js.snap, src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap, src/SmartComponents/DriftPage/__tests__/__snapshots__/DriftPage.tests.js.snap
In the comparison header, the system, baseline or HSP cell farthest to the left doesn't have a border on the left. This PR adds a border.
=> [DRFT-910] Add border to left most system in comparison header

src/App.scss, src/SmartComponents/DriftPage/DriftToolbar/DriftFilter/DriftFilter.js, src/SmartComponents/DriftPage/DriftToolbar/DriftFilter/DriftFilterDropdown.js, src/SmartComponents/DriftPage/DriftToolbar/DriftFilter/DriftFilterValue.js, src/SmartComponents/DriftPage/DriftToolbar/DriftFilter/__tests__/DriftFilterDropdown.tests.js, src/SmartComponents/DriftPage/DriftToolbar/DriftFilter/__tests__/DriftFilterValue.tests.js, src/SmartComponents/DriftPage/DriftToolbar/DriftFilter/__tests__/__snapshots__/DriftFilterDropdown.tests.js.snap, src/SmartComponents/DriftPage/DriftToolbar/DriftFilter/__tests__/__snapshots__/DriftFilterValue.tests.js.snap, src/SmartComponents/DriftPage/DriftToolbar/DriftToolbar.js, src/SmartComponents/DriftPage/DriftToolbar/__tests__/DriftToolbar.tests.js, src/SmartComponents/DriftPage/DriftToolbar/__tests__/__snapshots__/DriftToolbar.tests.js.snap, src/SmartComponents/DriftPage/__tests__/__snapshots__/DriftPage.tests.js.snap
Before, the comparison table filter had a fact name search filter and a state dropdown filter that were static in the toolbar. This PR adds a dropdown to select the type of filter you'd like to use (Fact name or state) and switches between the previously mentioned search filter and state dropdown filter depending on your dropdown selection.
To test:
- Go to drift app
- Click "Add to comparison" button (ensure you have at least one system or baseline)
- Select at least one system or baseline to create a comparison and click "Submit"
Test the filters and chips to ensure that filters are properly added and removed. Don't forget to test the feature when filtering by fact name that allows you to type a fact name filter and press enter. This allows to effectively set a filter and type in …
=> [DRFT-983] Change comparison filter to dropdown filter selector

src/SmartComponents/DriftPage/DriftPage.js, src/SmartComponents/DriftPage/DriftTable/DriftTable.js, src/SmartComponents/DriftPage/__tests__/__snapshots__/DriftPage.tests.js.snap
To test:
Create a comparison with at least one baseline that has at least one fact
Include the filter in the url for fact type filters `&filter[show]=baseline` like so: https://stage.foo.redhat.com:1337/insights/drift/?baseline_ids=<id>&reference_id=<id>&system_ids=<id>&filter[show]=baseline&filter[state]=same,different,incomplete_data&sort=-state,fact
This should load the comparison with the baseline only fact type filter set.
=> [DRFT-1007] Set fact type filters in url

src/SmartComponents/DriftPage/DriftTable/DriftTable.js
See #562. That PR was supposed to allow manual fact type filter changes in the url. But it was broken. Adding `&filter[show]=baseline` worked correctly, but if you added `&filter[show]=all` it would reset to show baseline facts only. This PR fixes that.
To test, try setting both `baseline` and `all` in the url and ensure that the table displays the correct filters.
=> [DRFT-1007] Fix fact type filters in url

config/setupTests.js, package-lock.json, package.json, src/SmartComponents/AddSystemModal/__tests__/AddSystemModal.tests.js, src/SmartComponents/GlobalFilterAlert/GlobalFilterAlert.js, src/SmartComponents/GlobalFilterAlert/__tests__/GlobalFilterAlert.fixtures.js, src/SmartComponents/GlobalFilterAlert/__tests__/GlobalFilterAlert.tests.js, src/SmartComponents/GlobalFilterAlert/__tests__/__snapshots__/GlobalFilterAlert.tests.js.snap, src/SmartComponents/SystemsTable/SystemsTable.js
To test, see DRFT-995 card on Interact sprint board for a video.
Otherwise
Navigate to Drift -> Comparison
Set SAP or Ansible Automation Platform in global filters
Click 'Add systems or baselines' button
What you'll get is an often incorrect display in the blue alert bar
about which filters are applied. Try selecting one, then the other, then
both, then none and you'll see that the value in the modal are often
incorrect.
This PR properly displays the selected workload filters.
=> [DRFT-995] Include Ansible in workloads filter

package-lock.json, package.json, src/App.scss, src/SmartComponents/DriftPage/DriftPage.js, src/SmartComponents/DriftPage/DriftTable/ComparisonHeader/ComparisonHeader.js, src/SmartComponents/DriftPage/DriftTable/ComparisonHeader/__tests__/__snapshots__/ComparisonHeader.tests.js.snap, src/SmartComponents/DriftPage/DriftTable/DriftTable.js, src/SmartComponents/DriftPage/DriftTable/DriftTableRow/RowFact.js, src/SmartComponents/DriftPage/DriftTable/__tests__/DriftTable.tests.js, src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap, src/SmartComponents/DriftPage/__tests__/__snapshots__/DriftPage.tests.js.snap
This PR makes the comparison table header and top scroll bar sticky to the top of the page.
To test, add various numbers of systems/baselines (specifically systems with facts so you can expand the facts and test the scroll).
The header of the table and top scrollbar should stick to the top of the page, and when you scroll right, the table contents should hide under the left two columns like they normally do.
Testing adding lots and a system or two to make sure that sizing remains in check. I had to split the header out of the table body. So I essentially had to create two tables and then use CSS to ensure that cell sizes update the same.
=> [DRFT-302] Make comparison header row sticky on scroll

config/dev.webpack.config.js
Included in [RHIF-27](https://issues.redhat.com/browse/RHIF-27).
Running Drift with `BETA=true` deploys to https://stage.foo.redhat.com:1337/insights/drift not https://stage.foo.redhat.com:1337/beta/insights/drift; this should this be changed to deploy to `/beta`
=> Correctly deploying to beta env locally

src/App.scss, src/SmartComponents/DriftPage/DriftTable/ComparisonHeader/ComparisonHeader.js, src/SmartComponents/DriftPage/DriftTable/ComparisonHeader/__tests__/ComparisonHeader.fixtures.js, src/SmartComponents/DriftPage/DriftTable/ComparisonHeader/__tests__/ComparisonHeader.tests.js, src/SmartComponents/DriftPage/DriftTable/ComparisonHeader/__tests__/__snapshots__/ComparisonHeader.tests.js.snap, src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap
New icons are present for systems in comparison. To test:
- Run a comparison with systems that are stale, do not have insights installed and do not have insights enabled. (These may be difficult to find or upload)
- Check the icons in the header row of the comparison table, they should be on the second row of the cells
This is how the icons should appear:
- If a system is stale, it will show the exclamation triangle icon.
- If a system does not have insights installed, then it will also not have insights enabled. This will show an icon and the tooltip will read "Insights not installed".
- If a system has insights installed, but does not have Insights enabled, it will show the same icon as before, but the tooltip will read "Insights not enabled".
- …
=> [DRFT-1042] Add icons for systems

src/App.scss, src/SmartComponents/AddSystemModal/AddSystemModal.js, src/SmartComponents/AddSystemModal/__tests__/AddSystemModal.tests.js, src/SmartComponents/AddSystemModal/__tests__/__snapshots__/AddSystemModal.tests.js.snap, src/SmartComponents/BaselinesPage/BaselinesPage.js, src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaselineToolbar/EditBaselineToolbar.js, src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaselineToolbar/__tests__/__snapshots__/EditBaselineToolbar.tests.js.snap, src/SmartComponents/BaselinesPage/__tests__/BaselinesPage.tests.js, src/SmartComponents/BaselinesPage/__tests__/__snapshots__/BaselinesPage.tests.js.snap, src/SmartComponents/BaselinesTable/BaselinesTable.js, src/SmartComponents/BaselinesTable/BaselinesToolbar/BaselinesToolbar.js, src/SmartComponents/BaselinesTable/BaselinesToolbar/__test__/BaselinesToolbar.test.js, src/SmartComponents/BaselinesTable/BaselinesToolbar/__test__/__snapshots__/BaselinesToolbar.test.js.snap, src/SmartComponents/BaselinesTable/__tests__/BaselinesTable.tests.js, src/SmartComponents/BaselinesTable/__tests__/__snapshots__/BaselinesTable.tests.js.snap, src/SmartComponents/BaselinesTable/redux/__tests__/helpers.tests.js, src/SmartComponents/BaselinesTable/redux/helpers.js, src/SmartComponents/SystemsTable/SystemsTable.js, src/SmartComponents/SystemsTable/__tests__/__snapshots__/SystemsTable.tests.js.snap, src/constants.js
Bulk selectors have been updated in 2 places for Drift:
- Baseline main page - Missing "Select page (#)" and counts for select none. We have removed 'Select all' from baseline list bulk select because there are no use cases that would utilize a full select of the baselines list and adding the ability to select all would cause some logic that would be a bit too complex for what we hope to achieve.
- Baseline detail page (If you click on a specific baseline to see its facts) - Missing counts for select none & select all
=> [DRFT-233] Update bulk selectors

src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaselineNameModal/EditBaselineNameModal.js, src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaselineNameModal/__tests__/__snapshots__/EditBaselineNameModal.tests.js.snap
In edit baseline name modal, the input title should read "Baseline name" instead of "Baseline title".
=> [DRFT-845] Change title in edit baseline name modal

src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaselineNameModal/EditBaselineNameModal.js, src/Utilities/Dispatcher.js
When you successfully change the name of a baseline, a success notification will appear on modal close.
Navigate to 'Baselines' -> select a baseline -> Click pencil icon the head to open the modal to change name.
=> [DRFT-371] Success notification to edit baseline name

src/SmartComponents/BaselinesTable/BaselinesToolbar/BaselinesToolbar.js
Before, if a user didn't have baselines write permissions, they would not be able to filter the baselines table. This PR adds the ability to filter without baselines write permissions.
=> [DRFT-1193] Enable filter on no baselines write

build.sh, deploy/frontend.yml, package.json, pr_check.sh
This patch contains the files / changes required for the consoledot containerization migration. Manifest:
- package.json disable jest cache in test
- deploy/frontend.yml is your new Frontend resource for k8s
- The two shell scripts are the build and PR check scripts for CI/CD
=> Build scripts, frontend resource, and jest config for migration

src/App.scss, src/SmartComponents/DriftPage/DriftTable/ComparisonHeader/ComparisonHeader.js, src/SmartComponents/DriftPage/DriftTable/ComparisonHeader/__tests__/ComparisonHeader.fixtures.js, src/SmartComponents/DriftPage/DriftTable/ComparisonHeader/__tests__/ComparisonHeader.tests.js, src/SmartComponents/DriftPage/DriftTable/ComparisonHeader/__tests__/__snapshots__/ComparisonHeader.tests.js.snap, src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap
To repro:
- Run a comparison
- See that the space between the system date and the historical profiles icon has no margin
This PR adds a margin.
This PR also reverts an old PR adding an icon to the system headers based on parameters in fetched data. There is a bug on the backend with no clear date of when to fix it. Rather than continuing to deal with keeping it in stage and reverting every time anyone wants to push to prod, I'm removing the code.
=> Add system header date margin

src/SmartComponents/DriftPage/DriftPage.js
Fixes the header layout for the Comparison page (/insights/draft). Before it took extra space around "Comparison" which looked differently from other pages.
=> fix(Comparison page): Fix the header layout

config/dev.ephemeral.webpack.config.js, config/dev.local.webpack.config.js, config/dev.stage.webpack.config.js, config/prod.webpack.config.js
Drift is down on Stage, everything works locally so I suspect it's caused by the missing react-router-dom in federated modules
=> Fix webpack config for router v6 upgrade

src/App.js
Drift was verifying inventory permissions by checking for `inventory:*:read`, but with the addition of `inventory:groups:read`, it changed how permission requests were returned. This PR specifically checks for `inventory:hosts:read`.
=> fix(RHINENG-1446): fix inventory permissions

src/Routes.js
To be consistent between other apps, Empty State should not be shown by default or when the request fails.
=> fix: Don't show empty state by default

src/SmartComponents/DriftPage/DriftTable/ComparisonHeader/ComparisonHeader.js, src/SmartComponents/DriftPage/DriftTable/ComparisonHeader/__tests__/ComparisonHeader.tests.js, src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap, src/SmartComponents/DriftPage/DriftToolbar/DriftToolbar.js
You will not see this bug on dev. In stage or prod, try comparing any 2 systems/baselines and run the comparison. Note that the column widths are not aligned on first load. If you resize the window it will update.
Check and make sure this still works in dev. We'll have to just merge and test in stage and see if it works, but I think it will.
=> fix(RHIENG-1025): fix comparison column width

src/App.js
Fixes https://issues.redhat.com/browse/ESSNTL-3721.
Set up the `inventory:host:read` permissions with excluding access (or just reach out to me how to find/setup the account and permissions - it's easier 😄). Go to /drift, click "Add systems or baselines", and make sure the modal table loads with the systems that are not member of any group.
=> fix(ESSNTL-3721): Fix inventory read permission check

src/SmartComponents/BaselinesPage/EditBaselinePage/SystemNotification/SystemNotification.js, src/SmartComponents/BaselinesPage/EditBaselinePage/SystemNotification/__tests__/SystemNotification.tests.js, src/SmartComponents/BaselinesPage/EditBaselinePage/SystemNotification/__tests__/__snapshots__/SystemNotification.tests.js.snap
Fixes https://issues.redhat.com/browse/ESSNTL-3722.
Check for inventory hosts read permissions on the baselines page: if the minimum is not met, then hide the associated systems table.
Assign your account Drift viewer role, and check any baseline's details page. You should not be able to access "Associated systems" because you are missing the inventory permissions.
Try to add the Inventory hosts read role (either group-level or general). Verify that you can open the tab now and the InventoryTable is loaded.
=> fix(ESSNTL-3722): Check for inventory permissions

src/SmartComponents/BaselinesPage/CreateBaselineModal/CreateBaselineModal.js, src/SmartComponents/BaselinesPage/CreateBaselineModal/__tests__/CreateBaselineModal.tests.js, src/SmartComponents/BaselinesPage/CreateBaselineModal/__tests__/__snapshots__/CreateBaselineModal.tests.js.snap, src/SmartComponents/BaselinesPage/__tests__/__snapshots__/BaselinesPage.tests.js.snap, src/SmartComponents/modules/reducers.js
Repro:
Navigate to Baselines
Click Create Baseline
Create baseline from scratch
Enter baseline name and click Create Baseline
The result in stage will be Error 400: malformed UUIDs (see screenshots).  However, the baseline does get created.
This is a react 18 bug and you won't be able to easily reproduce it in dev. It was an issue with a navigate trying to run before an api request had time to finish. It's part of the new feature with bulk requests.
You'll have to review the code, push to stage and check there to make sure it works.
=> fix(RHINENG-1032): create baseline navigates to undefined

src/App.scss, src/SmartComponents/DriftPage/DriftTable/ComparisonHeader/__tests__/ComparisonHeader.tests.js, src/SmartComponents/DriftPage/DriftTable/__tests__/__snapshots__/DriftTable.tests.js.snap, src/SmartComponents/HistoricalProfilesPopover/HistoricalProfilesCheckbox/HistoricalProfilesCheckbox.js, src/SmartComponents/HistoricalProfilesPopover/HistoricalProfilesCheckbox/__tests__/HistorialProfilesCheckbox.tests.js, src/SmartComponents/HistoricalProfilesPopover/HistoricalProfilesCheckbox/__tests__/__snapshots__/HistorialProfilesCheckbox.tests.js.snap, src/SmartComponents/HistoricalProfilesPopover/HistoricalProfilesPopover.js, src/SmartComponents/HistoricalProfilesPopover/__tests__/HistoricalProfilesPopover.tests.js, src/SmartComponents/HistoricalProfilesPopover/__tests__/__snapshots__/HistoricalProfilesPopover.tests.js.snap
Description:
I have a system with 4 hsps.  In the comparison modal, when I click on the hsp icon, it reports "There are no historical profiles to display".  See screenshot which shows in the Dev Tools window that the frontend is successfully retrieving the 4 hsps from the backend.
Steps to Reproduce:
1. Navigate to Operations -> Drift -> Comparison
2. Click Add systems or baselines
3. For a system that has hsps, click on the hsp icon. It reports no hsps. *Make sure via the Network tab in dev tools that the hsps fetch actually fetched hsps*
How reproducible: (Always / Intermittent / Random) Always
Actual Results:
No hsps reported
Expected results:
A popup window that allows me to select hsps
=> fix(RHINENG-1457): hsp dropdown not displaying hsps

config/dev.webpack.config.js, config/prod.webpack.config.js
checks for if the variable is true, as opposed to if it exist, because javascript.
=> fix(webpack): update webpack config to account for JS rules

src/Routes.js
The `?filter[system_profile][operating_system][RHEL][version][gte]=0` filter has been added to the inventory hosts fetch. This filter ultimately checks for the count of RHEL systems in inventory. So, if a user has only non-RHEL systems (think CentOS only) then the App Zero State will be shown.
=> chore(RHINENG-5919): App Zero State checks RHEL only

config/setupTests.js, src/SmartComponents/AddSystemModal/__tests__/__snapshots__/AddSystemModal.tests.js.snap, src/SmartComponents/BaselinesPage/EditBaselinePage/SystemNotification/__tests__/__snapshots__/SystemNotification.tests.js.snap, src/SmartComponents/SystemsTable/SystemsTable.js, src/SmartComponents/SystemsTable/__tests__/SystemsTable.tests.js, src/SmartComponents/SystemsTable/__tests__/__snapshots__/NotificationsSystemsTable.tests.js.snap, src/SmartComponents/SystemsTable/__tests__/__snapshots__/SystemsTable.tests.js.snap
Fixes https://issues.redhat.com/browse/RHINENG-5473.
This makes sure no modals show CentOS systems nor allowing users to filter out the CentOS systems. Drift only supports RHEL systems at the moment.
1. Use an account with at least one CentOS system registered in Inventory
2. Go to /insights/drift and verify that you are not able to add any CentOS system to comparison
3. Create or navigate to any baselines, switch to Associated systems
4. Make sure you are the same way not able to associate any CentOS system with this baseline.
=> fix(RHINENG-5473): Do not show CentOS systems in modals
